package com.ztesoft.zsmart.nros.sbc.user.dao.dataobject.generator;

import java.io.Serializable;

/**
 * EnumConfigDO
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-04-20
 */
public class EnumConfigDO implements Serializable {
    /**
     * EnumConfigDO-id
     */
    private Long id;

    /**
     * EnumConfigDO-field_code
     */
    private String fieldCode;

    /**
     * EnumConfigDO-field_name
     */
    private String fieldName;

    /**
     * EnumConfigDO-table_code
     */
    private String tableCode;

    /**
     * EnumConfigDO-table_name
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：EnumConfigDO-id
     *
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：EnumConfigDO-id
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：EnumConfigDO-field_code
     *
     * @return field_code
     */
    public String getFieldCode() {
        return fieldCode;
    }

    /**
     * 设置：EnumConfigDO-field_code
     *
     * @param fieldCode
     */
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode == null ? null : fieldCode.trim();
    }

    /**
     * 获取：EnumConfigDO-field_name
     *
     * @return field_name
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * 设置：EnumConfigDO-field_name
     *
     * @param fieldName
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * 获取：EnumConfigDO-table_code
     *
     * @return table_code
     */
    public String getTableCode() {
        return tableCode;
    }

    /**
     * 设置：EnumConfigDO-table_code
     *
     * @param tableCode
     */
    public void setTableCode(String tableCode) {
        this.tableCode = tableCode == null ? null : tableCode.trim();
    }

    /**
     * 获取：EnumConfigDO-table_name
     *
     * @return table_name
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * 设置：EnumConfigDO-table_name
     *
     * @param tableName
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }
}