package com.ztesoft.zsmart.nros.sbc.user.dao.dataobject.generator;

import java.io.Serializable;
import java.util.Date;

/**
 * SubsidiaryDO
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-04-25
 */
public class SubsidiaryDO implements Serializable {
    /**
     * SubsidiaryDO-主键
     */
    private Long id;

    /**
     * SubsidiaryDO-创建时间
     */
    private Date gmtCreate;

    /**
     * SubsidiaryDO-修改时间
     */
    private Date gmtModified;

    /**
     * SubsidiaryDO-创建者
     */
    private String creator;

    /**
     * SubsidiaryDO-修改者
     */
    private String modifier;

    /**
     * SubsidiaryDO-乐观锁版本号
     */
    private Long version;

    /**
     * SubsidiaryDO-是否启用(0,1)
     */
    private String active;

    /**
     * SubsidiaryDO-机构逻辑主键(同盒马merchant_id)
     */
    private Long orgId;

    /**
     * SubsidiaryDO-名称
     */
    private String name;

    /**
     * SubsidiaryDO-负责人
     */
    private String principal;

    /**
     * SubsidiaryDO-联系人电话
     */
    private String phone;

    /**
     * SubsidiaryDO-传真
     */
    private String fax;

    /**
     * SubsidiaryDO-支付宝账号
     */
    private String alipayAccount;

    /**
     * SubsidiaryDO-分账费率
     */
    private Long ledgerAccountRate;

    /**
     * SubsidiaryDO-备注
     */
    private String remark;

    /**
     * SubsidiaryDO-编码
     */
    private String code;

    /**
     * SubsidiaryDO-省
     */
    private String province;

    /**
     * SubsidiaryDO-市
     */
    private String city;

    /**
     * SubsidiaryDO-区
     */
    private String area;

    /**
     * SubsidiaryDO-详细地址
     */
    private String address;

    /**
     * SubsidiaryDO-扩展字段
     */
    private String extension;

    /**
     * SubsidiaryDO-上级机构id
     */
    private Long parentOrgId;

    /**
     * SubsidiaryDO-state
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：SubsidiaryDO-主键
     *
     * @return 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：SubsidiaryDO-主键
     *
     * @param id SubsidiaryDO-主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：SubsidiaryDO-创建时间
     *
     * @return 创建时间
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * 设置：SubsidiaryDO-创建时间
     *
     * @param gmtCreate SubsidiaryDO-创建时间
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * 获取：SubsidiaryDO-修改时间
     *
     * @return 修改时间
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * 设置：SubsidiaryDO-修改时间
     *
     * @param gmtModified SubsidiaryDO-修改时间
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * 获取：SubsidiaryDO-创建者
     *
     * @return 创建者
     */
    public String getCreator() {
        return creator;
    }

    /**
     * 设置：SubsidiaryDO-创建者
     *
     * @param creator SubsidiaryDO-创建者
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * 获取：SubsidiaryDO-修改者
     *
     * @return 修改者
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * 设置：SubsidiaryDO-修改者
     *
     * @param modifier SubsidiaryDO-修改者
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * 获取：SubsidiaryDO-乐观锁版本号
     *
     * @return 乐观锁版本号
     */
    public Long getVersion() {
        return version;
    }

    /**
     * 设置：SubsidiaryDO-乐观锁版本号
     *
     * @param version SubsidiaryDO-乐观锁版本号
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * 获取：SubsidiaryDO-是否启用(0,1)
     *
     * @return 是否启用(0,1)
     */
    public String getActive() {
        return active;
    }

    /**
     * 设置：SubsidiaryDO-是否启用(0,1)
     *
     * @param active SubsidiaryDO-是否启用(0,1)
     */
    public void setActive(String active) {
        this.active = active == null ? null : active.trim();
    }

    /**
     * 获取：SubsidiaryDO-机构逻辑主键(同盒马merchant_id)
     *
     * @return 机构逻辑主键(同盒马merchant_id)
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置：SubsidiaryDO-机构逻辑主键(同盒马merchant_id)
     *
     * @param orgId SubsidiaryDO-机构逻辑主键(同盒马merchant_id)
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取：SubsidiaryDO-名称
     *
     * @return 名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置：SubsidiaryDO-名称
     *
     * @param name SubsidiaryDO-名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取：SubsidiaryDO-负责人
     *
     * @return 负责人
     */
    public String getPrincipal() {
        return principal;
    }

    /**
     * 设置：SubsidiaryDO-负责人
     *
     * @param principal SubsidiaryDO-负责人
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * 获取：SubsidiaryDO-联系人电话
     *
     * @return 联系人电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置：SubsidiaryDO-联系人电话
     *
     * @param phone SubsidiaryDO-联系人电话
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取：SubsidiaryDO-传真
     *
     * @return 传真
     */
    public String getFax() {
        return fax;
    }

    /**
     * 设置：SubsidiaryDO-传真
     *
     * @param fax SubsidiaryDO-传真
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * 获取：SubsidiaryDO-支付宝账号
     *
     * @return 支付宝账号
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * 设置：SubsidiaryDO-支付宝账号
     *
     * @param alipayAccount SubsidiaryDO-支付宝账号
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
    }

    /**
     * 获取：SubsidiaryDO-分账费率
     *
     * @return 分账费率
     */
    public Long getLedgerAccountRate() {
        return ledgerAccountRate;
    }

    /**
     * 设置：SubsidiaryDO-分账费率
     *
     * @param ledgerAccountRate SubsidiaryDO-分账费率
     */
    public void setLedgerAccountRate(Long ledgerAccountRate) {
        this.ledgerAccountRate = ledgerAccountRate;
    }

    /**
     * 获取：SubsidiaryDO-备注
     *
     * @return 备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     * 设置：SubsidiaryDO-备注
     *
     * @param remark SubsidiaryDO-备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * 获取：SubsidiaryDO-编码
     *
     * @return 编码
     */
    public String getCode() {
        return code;
    }

    /**
     * 设置：SubsidiaryDO-编码
     *
     * @param code SubsidiaryDO-编码
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * 获取：SubsidiaryDO-省
     *
     * @return 省
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置：SubsidiaryDO-省
     *
     * @param province SubsidiaryDO-省
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * 获取：SubsidiaryDO-市
     *
     * @return 市
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置：SubsidiaryDO-市
     *
     * @param city SubsidiaryDO-市
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取：SubsidiaryDO-区
     *
     * @return 区
     */
    public String getArea() {
        return area;
    }

    /**
     * 设置：SubsidiaryDO-区
     *
     * @param area SubsidiaryDO-区
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * 获取：SubsidiaryDO-详细地址
     *
     * @return 详细地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置：SubsidiaryDO-详细地址
     *
     * @param address SubsidiaryDO-详细地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取：SubsidiaryDO-扩展字段
     *
     * @return 扩展字段
     */
    public String getExtension() {
        return extension;
    }

    /**
     * 设置：SubsidiaryDO-扩展字段
     *
     * @param extension SubsidiaryDO-扩展字段
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * 获取：SubsidiaryDO-上级机构id
     *
     * @return 上级机构id
     */
    public Long getParentOrgId() {
        return parentOrgId;
    }

    /**
     * 设置：SubsidiaryDO-上级机构id
     *
     * @param parentOrgId SubsidiaryDO-上级机构id
     */
    public void setParentOrgId(Long parentOrgId) {
        this.parentOrgId = parentOrgId;
    }

    /**
     * 获取：SubsidiaryDO-state
     *
     * @return state
     */
    public String getState() {
        return state;
    }

    /**
     * 设置：SubsidiaryDO-state
     *
     * @param state
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}