package com.ztesoft.zsmart.nros.sbc.user.dao.dataobject.generator;

import java.io.Serializable;
import java.util.Date;

/**
 * UserOrgPrivDO
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-07
 */
public class UserOrgPrivDO implements Serializable {
    /**
     * UserOrgPrivDO-id
     */
    private Long id;

    /**
     * UserOrgPrivDO-user_id
     */
    private Long userId;

    /**
     * UserOrgPrivDO-org_id
     */
    private Long orgId;

    /**
     * UserOrgPrivDO-gmt_create
     */
    private Date gmtCreate;

    /**
     * UserOrgPrivDO-creator
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：UserOrgPrivDO-id
     *
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：UserOrgPrivDO-id
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：UserOrgPrivDO-user_id
     *
     * @return user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 设置：UserOrgPrivDO-user_id
     *
     * @param userId
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 获取：UserOrgPrivDO-org_id
     *
     * @return org_id
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置：UserOrgPrivDO-org_id
     *
     * @param orgId
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取：UserOrgPrivDO-gmt_create
     *
     * @return gmt_create
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * 设置：UserOrgPrivDO-gmt_create
     *
     * @param gmtCreate
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * 获取：UserOrgPrivDO-creator
     *
     * @return creator
     */
    public String getCreator() {
        return creator;
    }

    /**
     * 设置：UserOrgPrivDO-creator
     *
     * @param creator
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }
}