package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 商品主数据
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58A4102DO implements Serializable {
    /**
     * 商品主数据-MMMCU
     */
    private String mmmcu;

    /**
     * 商品主数据-MMLITM
     */
    private String mmlitm;

    /**
     * 商品主数据-MMITM
     */
    private Integer mmitm;

    /**
     * 商品主数据-MMSRP1
     */
    private String mmsrp1;

    /**
     * 商品主数据-MMDL01
     */
    private String mmdl01;

    /**
     * 商品主数据-MMSRP2
     */
    private String mmsrp2;

    /**
     * 商品主数据-MMDL02
     */
    private String mmdl02;

    /**
     * 商品主数据-MMSRP3
     */
    private String mmsrp3;

    /**
     * 商品主数据-MMDL03
     */
    private String mmdl03;

    /**
     * 商品主数据-MMSRP4
     */
    private String mmsrp4;

    /**
     * 商品主数据-MMDL04
     */
    private String mmdl04;

    /**
     * 商品主数据-MMSRP5
     */
    private String mmsrp5;

    /**
     * 商品主数据-MMDL05
     */
    private String mmdl05;

    /**
     * 商品主数据-MMSRP6
     */
    private String mmsrp6;

    /**
     * 商品主数据-MMDL06
     */
    private String mmdl06;

    /**
     * 商品主数据-MMSRP7
     */
    private String mmsrp7;

    /**
     * 商品主数据-MMDL07
     */
    private String mmdl07;

    /**
     * 商品主数据-MMSRP8
     */
    private String mmsrp8;

    /**
     * 商品主数据-MMDL08
     */
    private String mmdl08;

    /**
     * 商品主数据-MMSRP9
     */
    private String mmsrp9;

    /**
     * 商品主数据-MMDL09
     */
    private String mmdl09;

    /**
     * 商品主数据-MMSRP0
     */
    private String mmsrp0;

    /**
     * 商品主数据-MMDL10
     */
    private String mmdl10;

    /**
     * 商品主数据-MMPRP1
     */
    private String mmprp1;

    /**
     * 商品主数据-MMDL11
     */
    private String mmdl11;

    /**
     * 商品主数据-MMPRP2
     */
    private String mmprp2;

    /**
     * 商品主数据-MMDL12
     */
    private String mmdl12;

    /**
     * 商品主数据-MMCITM
     */
    private String mmcitm;

    /**
     * 商品主数据-MMSRTX
     */
    private String mmsrtx;

    /**
     * 商品主数据-MMDSC3
     */
    private String mmdsc3;

    /**
     * 商品主数据-MMUOM1
     */
    private String mmuom1;

    /**
     * 商品主数据-MMDL13
     */
    private String mmdl13;

    /**
     * 商品主数据-MMMKT3
     */
    private String mmmkt3;

    /**
     * 商品主数据-MMDSC1
     */
    private String mmdsc1;

    /**
     * 商品主数据-MMDSC2
     */
    private String mmdsc2;

    /**
     * 商品主数据-MMSLD
     */
    private String mmsld;

    /**
     * 商品主数据-MMDL14
     */
    private String mmdl14;

    /**
     * 商品主数据-MMCONV
     */
    private String mmconv;

    /**
     * 商品主数据-MMSRCE
     */
    private String mmsrce;

    /**
     * 商品主数据-MMSTKT
     */
    private String mmstkt;

    /**
     * 商品主数据-MMGLPT
     */
    private String mmglpt;

    /**
     * 商品主数据-MMVEND
     */
    private Integer mmvend;

    /**
     * 商品主数据-MMALPH
     */
    private String mmalph;

    /**
     * 商品主数据-MMUSER
     */
    private String mmuser;

    /**
     * 商品主数据-MMPID
     */
    private String mmpid;

    /**
     * 商品主数据-MMJOBN
     */
    private String mmjobn;

    /**
     * 商品主数据-MMUPMJ
     */
    private Date mmupmj;

    /**
     * 商品主数据-MMTDAY
     */
    private String mmtday;

    /**
     * 商品主数据-标识
     */
    private String mmflag;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：商品主数据-MMMCU
     *
     * @return MMMCU
     */
    public String getMmmcu() {
        return mmmcu;
    }

    /**
     * 设置：商品主数据-MMMCU
     *
     * @param mmmcu
     */
    public void setMmmcu(String mmmcu) {
        this.mmmcu = mmmcu == null ? null : mmmcu.trim();
    }

    /**
     * 获取：商品主数据-MMLITM
     *
     * @return MMLITM
     */
    public String getMmlitm() {
        return mmlitm;
    }

    /**
     * 设置：商品主数据-MMLITM
     *
     * @param mmlitm
     */
    public void setMmlitm(String mmlitm) {
        this.mmlitm = mmlitm == null ? null : mmlitm.trim();
    }

    /**
     * 获取：商品主数据-MMITM
     *
     * @return MMITM
     */
    public Integer getMmitm() {
        return mmitm;
    }

    /**
     * 设置：商品主数据-MMITM
     *
     * @param mmitm
     */
    public void setMmitm(Integer mmitm) {
        this.mmitm = mmitm;
    }

    /**
     * 获取：商品主数据-MMSRP1
     *
     * @return MMSRP1
     */
    public String getMmsrp1() {
        return mmsrp1;
    }

    /**
     * 设置：商品主数据-MMSRP1
     *
     * @param mmsrp1
     */
    public void setMmsrp1(String mmsrp1) {
        this.mmsrp1 = mmsrp1 == null ? null : mmsrp1.trim();
    }

    /**
     * 获取：商品主数据-MMDL01
     *
     * @return MMDL01
     */
    public String getMmdl01() {
        return mmdl01;
    }

    /**
     * 设置：商品主数据-MMDL01
     *
     * @param mmdl01
     */
    public void setMmdl01(String mmdl01) {
        this.mmdl01 = mmdl01 == null ? null : mmdl01.trim();
    }

    /**
     * 获取：商品主数据-MMSRP2
     *
     * @return MMSRP2
     */
    public String getMmsrp2() {
        return mmsrp2;
    }

    /**
     * 设置：商品主数据-MMSRP2
     *
     * @param mmsrp2
     */
    public void setMmsrp2(String mmsrp2) {
        this.mmsrp2 = mmsrp2 == null ? null : mmsrp2.trim();
    }

    /**
     * 获取：商品主数据-MMDL02
     *
     * @return MMDL02
     */
    public String getMmdl02() {
        return mmdl02;
    }

    /**
     * 设置：商品主数据-MMDL02
     *
     * @param mmdl02
     */
    public void setMmdl02(String mmdl02) {
        this.mmdl02 = mmdl02 == null ? null : mmdl02.trim();
    }

    /**
     * 获取：商品主数据-MMSRP3
     *
     * @return MMSRP3
     */
    public String getMmsrp3() {
        return mmsrp3;
    }

    /**
     * 设置：商品主数据-MMSRP3
     *
     * @param mmsrp3
     */
    public void setMmsrp3(String mmsrp3) {
        this.mmsrp3 = mmsrp3 == null ? null : mmsrp3.trim();
    }

    /**
     * 获取：商品主数据-MMDL03
     *
     * @return MMDL03
     */
    public String getMmdl03() {
        return mmdl03;
    }

    /**
     * 设置：商品主数据-MMDL03
     *
     * @param mmdl03
     */
    public void setMmdl03(String mmdl03) {
        this.mmdl03 = mmdl03 == null ? null : mmdl03.trim();
    }

    /**
     * 获取：商品主数据-MMSRP4
     *
     * @return MMSRP4
     */
    public String getMmsrp4() {
        return mmsrp4;
    }

    /**
     * 设置：商品主数据-MMSRP4
     *
     * @param mmsrp4
     */
    public void setMmsrp4(String mmsrp4) {
        this.mmsrp4 = mmsrp4 == null ? null : mmsrp4.trim();
    }

    /**
     * 获取：商品主数据-MMDL04
     *
     * @return MMDL04
     */
    public String getMmdl04() {
        return mmdl04;
    }

    /**
     * 设置：商品主数据-MMDL04
     *
     * @param mmdl04
     */
    public void setMmdl04(String mmdl04) {
        this.mmdl04 = mmdl04 == null ? null : mmdl04.trim();
    }

    /**
     * 获取：商品主数据-MMSRP5
     *
     * @return MMSRP5
     */
    public String getMmsrp5() {
        return mmsrp5;
    }

    /**
     * 设置：商品主数据-MMSRP5
     *
     * @param mmsrp5
     */
    public void setMmsrp5(String mmsrp5) {
        this.mmsrp5 = mmsrp5 == null ? null : mmsrp5.trim();
    }

    /**
     * 获取：商品主数据-MMDL05
     *
     * @return MMDL05
     */
    public String getMmdl05() {
        return mmdl05;
    }

    /**
     * 设置：商品主数据-MMDL05
     *
     * @param mmdl05
     */
    public void setMmdl05(String mmdl05) {
        this.mmdl05 = mmdl05 == null ? null : mmdl05.trim();
    }

    /**
     * 获取：商品主数据-MMSRP6
     *
     * @return MMSRP6
     */
    public String getMmsrp6() {
        return mmsrp6;
    }

    /**
     * 设置：商品主数据-MMSRP6
     *
     * @param mmsrp6
     */
    public void setMmsrp6(String mmsrp6) {
        this.mmsrp6 = mmsrp6 == null ? null : mmsrp6.trim();
    }

    /**
     * 获取：商品主数据-MMDL06
     *
     * @return MMDL06
     */
    public String getMmdl06() {
        return mmdl06;
    }

    /**
     * 设置：商品主数据-MMDL06
     *
     * @param mmdl06
     */
    public void setMmdl06(String mmdl06) {
        this.mmdl06 = mmdl06 == null ? null : mmdl06.trim();
    }

    /**
     * 获取：商品主数据-MMSRP7
     *
     * @return MMSRP7
     */
    public String getMmsrp7() {
        return mmsrp7;
    }

    /**
     * 设置：商品主数据-MMSRP7
     *
     * @param mmsrp7
     */
    public void setMmsrp7(String mmsrp7) {
        this.mmsrp7 = mmsrp7 == null ? null : mmsrp7.trim();
    }

    /**
     * 获取：商品主数据-MMDL07
     *
     * @return MMDL07
     */
    public String getMmdl07() {
        return mmdl07;
    }

    /**
     * 设置：商品主数据-MMDL07
     *
     * @param mmdl07
     */
    public void setMmdl07(String mmdl07) {
        this.mmdl07 = mmdl07 == null ? null : mmdl07.trim();
    }

    /**
     * 获取：商品主数据-MMSRP8
     *
     * @return MMSRP8
     */
    public String getMmsrp8() {
        return mmsrp8;
    }

    /**
     * 设置：商品主数据-MMSRP8
     *
     * @param mmsrp8
     */
    public void setMmsrp8(String mmsrp8) {
        this.mmsrp8 = mmsrp8 == null ? null : mmsrp8.trim();
    }

    /**
     * 获取：商品主数据-MMDL08
     *
     * @return MMDL08
     */
    public String getMmdl08() {
        return mmdl08;
    }

    /**
     * 设置：商品主数据-MMDL08
     *
     * @param mmdl08
     */
    public void setMmdl08(String mmdl08) {
        this.mmdl08 = mmdl08 == null ? null : mmdl08.trim();
    }

    /**
     * 获取：商品主数据-MMSRP9
     *
     * @return MMSRP9
     */
    public String getMmsrp9() {
        return mmsrp9;
    }

    /**
     * 设置：商品主数据-MMSRP9
     *
     * @param mmsrp9
     */
    public void setMmsrp9(String mmsrp9) {
        this.mmsrp9 = mmsrp9 == null ? null : mmsrp9.trim();
    }

    /**
     * 获取：商品主数据-MMDL09
     *
     * @return MMDL09
     */
    public String getMmdl09() {
        return mmdl09;
    }

    /**
     * 设置：商品主数据-MMDL09
     *
     * @param mmdl09
     */
    public void setMmdl09(String mmdl09) {
        this.mmdl09 = mmdl09 == null ? null : mmdl09.trim();
    }

    /**
     * 获取：商品主数据-MMSRP0
     *
     * @return MMSRP0
     */
    public String getMmsrp0() {
        return mmsrp0;
    }

    /**
     * 设置：商品主数据-MMSRP0
     *
     * @param mmsrp0
     */
    public void setMmsrp0(String mmsrp0) {
        this.mmsrp0 = mmsrp0 == null ? null : mmsrp0.trim();
    }

    /**
     * 获取：商品主数据-MMDL10
     *
     * @return MMDL10
     */
    public String getMmdl10() {
        return mmdl10;
    }

    /**
     * 设置：商品主数据-MMDL10
     *
     * @param mmdl10
     */
    public void setMmdl10(String mmdl10) {
        this.mmdl10 = mmdl10 == null ? null : mmdl10.trim();
    }

    /**
     * 获取：商品主数据-MMPRP1
     *
     * @return MMPRP1
     */
    public String getMmprp1() {
        return mmprp1;
    }

    /**
     * 设置：商品主数据-MMPRP1
     *
     * @param mmprp1
     */
    public void setMmprp1(String mmprp1) {
        this.mmprp1 = mmprp1 == null ? null : mmprp1.trim();
    }

    /**
     * 获取：商品主数据-MMDL11
     *
     * @return MMDL11
     */
    public String getMmdl11() {
        return mmdl11;
    }

    /**
     * 设置：商品主数据-MMDL11
     *
     * @param mmdl11
     */
    public void setMmdl11(String mmdl11) {
        this.mmdl11 = mmdl11 == null ? null : mmdl11.trim();
    }

    /**
     * 获取：商品主数据-MMPRP2
     *
     * @return MMPRP2
     */
    public String getMmprp2() {
        return mmprp2;
    }

    /**
     * 设置：商品主数据-MMPRP2
     *
     * @param mmprp2
     */
    public void setMmprp2(String mmprp2) {
        this.mmprp2 = mmprp2 == null ? null : mmprp2.trim();
    }

    /**
     * 获取：商品主数据-MMDL12
     *
     * @return MMDL12
     */
    public String getMmdl12() {
        return mmdl12;
    }

    /**
     * 设置：商品主数据-MMDL12
     *
     * @param mmdl12
     */
    public void setMmdl12(String mmdl12) {
        this.mmdl12 = mmdl12 == null ? null : mmdl12.trim();
    }

    /**
     * 获取：商品主数据-MMCITM
     *
     * @return MMCITM
     */
    public String getMmcitm() {
        return mmcitm;
    }

    /**
     * 设置：商品主数据-MMCITM
     *
     * @param mmcitm
     */
    public void setMmcitm(String mmcitm) {
        this.mmcitm = mmcitm == null ? null : mmcitm.trim();
    }

    /**
     * 获取：商品主数据-MMSRTX
     *
     * @return MMSRTX
     */
    public String getMmsrtx() {
        return mmsrtx;
    }

    /**
     * 设置：商品主数据-MMSRTX
     *
     * @param mmsrtx
     */
    public void setMmsrtx(String mmsrtx) {
        this.mmsrtx = mmsrtx == null ? null : mmsrtx.trim();
    }

    /**
     * 获取：商品主数据-MMDSC3
     *
     * @return MMDSC3
     */
    public String getMmdsc3() {
        return mmdsc3;
    }

    /**
     * 设置：商品主数据-MMDSC3
     *
     * @param mmdsc3
     */
    public void setMmdsc3(String mmdsc3) {
        this.mmdsc3 = mmdsc3 == null ? null : mmdsc3.trim();
    }

    /**
     * 获取：商品主数据-MMUOM1
     *
     * @return MMUOM1
     */
    public String getMmuom1() {
        return mmuom1;
    }

    /**
     * 设置：商品主数据-MMUOM1
     *
     * @param mmuom1
     */
    public void setMmuom1(String mmuom1) {
        this.mmuom1 = mmuom1 == null ? null : mmuom1.trim();
    }

    /**
     * 获取：商品主数据-MMDL13
     *
     * @return MMDL13
     */
    public String getMmdl13() {
        return mmdl13;
    }

    /**
     * 设置：商品主数据-MMDL13
     *
     * @param mmdl13
     */
    public void setMmdl13(String mmdl13) {
        this.mmdl13 = mmdl13 == null ? null : mmdl13.trim();
    }

    /**
     * 获取：商品主数据-MMMKT3
     *
     * @return MMMKT3
     */
    public String getMmmkt3() {
        return mmmkt3;
    }

    /**
     * 设置：商品主数据-MMMKT3
     *
     * @param mmmkt3
     */
    public void setMmmkt3(String mmmkt3) {
        this.mmmkt3 = mmmkt3 == null ? null : mmmkt3.trim();
    }

    /**
     * 获取：商品主数据-MMDSC1
     *
     * @return MMDSC1
     */
    public String getMmdsc1() {
        return mmdsc1;
    }

    /**
     * 设置：商品主数据-MMDSC1
     *
     * @param mmdsc1
     */
    public void setMmdsc1(String mmdsc1) {
        this.mmdsc1 = mmdsc1 == null ? null : mmdsc1.trim();
    }

    /**
     * 获取：商品主数据-MMDSC2
     *
     * @return MMDSC2
     */
    public String getMmdsc2() {
        return mmdsc2;
    }

    /**
     * 设置：商品主数据-MMDSC2
     *
     * @param mmdsc2
     */
    public void setMmdsc2(String mmdsc2) {
        this.mmdsc2 = mmdsc2 == null ? null : mmdsc2.trim();
    }

    /**
     * 获取：商品主数据-MMSLD
     *
     * @return MMSLD
     */
    public String getMmsld() {
        return mmsld;
    }

    /**
     * 设置：商品主数据-MMSLD
     *
     * @param mmsld
     */
    public void setMmsld(String mmsld) {
        this.mmsld = mmsld == null ? null : mmsld.trim();
    }

    /**
     * 获取：商品主数据-MMDL14
     *
     * @return MMDL14
     */
    public String getMmdl14() {
        return mmdl14;
    }

    /**
     * 设置：商品主数据-MMDL14
     *
     * @param mmdl14
     */
    public void setMmdl14(String mmdl14) {
        this.mmdl14 = mmdl14 == null ? null : mmdl14.trim();
    }

    /**
     * 获取：商品主数据-MMCONV
     *
     * @return MMCONV
     */
    public String getMmconv() {
        return mmconv;
    }

    /**
     * 设置：商品主数据-MMCONV
     *
     * @param mmconv
     */
    public void setMmconv(String mmconv) {
        this.mmconv = mmconv == null ? null : mmconv.trim();
    }

    /**
     * 获取：商品主数据-MMSRCE
     *
     * @return MMSRCE
     */
    public String getMmsrce() {
        return mmsrce;
    }

    /**
     * 设置：商品主数据-MMSRCE
     *
     * @param mmsrce
     */
    public void setMmsrce(String mmsrce) {
        this.mmsrce = mmsrce == null ? null : mmsrce.trim();
    }

    /**
     * 获取：商品主数据-MMSTKT
     *
     * @return MMSTKT
     */
    public String getMmstkt() {
        return mmstkt;
    }

    /**
     * 设置：商品主数据-MMSTKT
     *
     * @param mmstkt
     */
    public void setMmstkt(String mmstkt) {
        this.mmstkt = mmstkt == null ? null : mmstkt.trim();
    }

    /**
     * 获取：商品主数据-MMGLPT
     *
     * @return MMGLPT
     */
    public String getMmglpt() {
        return mmglpt;
    }

    /**
     * 设置：商品主数据-MMGLPT
     *
     * @param mmglpt
     */
    public void setMmglpt(String mmglpt) {
        this.mmglpt = mmglpt == null ? null : mmglpt.trim();
    }

    /**
     * 获取：商品主数据-MMVEND
     *
     * @return MMVEND
     */
    public Integer getMmvend() {
        return mmvend;
    }

    /**
     * 设置：商品主数据-MMVEND
     *
     * @param mmvend
     */
    public void setMmvend(Integer mmvend) {
        this.mmvend = mmvend;
    }

    /**
     * 获取：商品主数据-MMALPH
     *
     * @return MMALPH
     */
    public String getMmalph() {
        return mmalph;
    }

    /**
     * 设置：商品主数据-MMALPH
     *
     * @param mmalph
     */
    public void setMmalph(String mmalph) {
        this.mmalph = mmalph == null ? null : mmalph.trim();
    }

    /**
     * 获取：商品主数据-MMUSER
     *
     * @return MMUSER
     */
    public String getMmuser() {
        return mmuser;
    }

    /**
     * 设置：商品主数据-MMUSER
     *
     * @param mmuser
     */
    public void setMmuser(String mmuser) {
        this.mmuser = mmuser == null ? null : mmuser.trim();
    }

    /**
     * 获取：商品主数据-MMPID
     *
     * @return MMPID
     */
    public String getMmpid() {
        return mmpid;
    }

    /**
     * 设置：商品主数据-MMPID
     *
     * @param mmpid
     */
    public void setMmpid(String mmpid) {
        this.mmpid = mmpid == null ? null : mmpid.trim();
    }

    /**
     * 获取：商品主数据-MMJOBN
     *
     * @return MMJOBN
     */
    public String getMmjobn() {
        return mmjobn;
    }

    /**
     * 设置：商品主数据-MMJOBN
     *
     * @param mmjobn
     */
    public void setMmjobn(String mmjobn) {
        this.mmjobn = mmjobn == null ? null : mmjobn.trim();
    }

    /**
     * 获取：商品主数据-MMUPMJ
     *
     * @return MMUPMJ
     */
    public Date getMmupmj() {
        return mmupmj;
    }

    /**
     * 设置：商品主数据-MMUPMJ
     *
     * @param mmupmj
     */
    public void setMmupmj(Date mmupmj) {
        this.mmupmj = mmupmj;
    }

    /**
     * 获取：商品主数据-MMTDAY
     *
     * @return MMTDAY
     */
    public String getMmtday() {
        return mmtday;
    }

    /**
     * 设置：商品主数据-MMTDAY
     *
     * @param mmtday
     */
    public void setMmtday(String mmtday) {
        this.mmtday = mmtday == null ? null : mmtday.trim();
    }

    /**
     * 获取：商品主数据-标识
     *
     * @return 标识
     */
    public String getMmflag() {
        return mmflag;
    }

    /**
     * 设置：商品主数据-标识
     *
     * @param mmflag 商品主数据-标识
     */
    public void setMmflag(String mmflag) {
        this.mmflag = mmflag == null ? null : mmflag.trim();
    }
}