package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 库存表
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58A4021DO implements Serializable {
    /**
     * 库存表-ZTLITM
     */
    private String ztlitm;

    /**
     * 库存表-ZTUORG
     */
    private Integer ztuorg;

    /**
     * 库存表-ZTLOTN
     */
    private String ztlotn;

    /**
     * 库存表-日期
     */
    private Date ztupmj;

    /**
     * 库存表-时间
     */
    private String ztupmt;

    /**
     * 库存表-标识
     */
    private String ztflag;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：库存表-ZTLITM
     *
     * @return ZTLITM
     */
    public String getZtlitm() {
        return ztlitm;
    }

    /**
     * 设置：库存表-ZTLITM
     *
     * @param ztlitm
     */
    public void setZtlitm(String ztlitm) {
        this.ztlitm = ztlitm == null ? null : ztlitm.trim();
    }

    /**
     * 获取：库存表-ZTUORG
     *
     * @return ZTUORG
     */
    public Integer getZtuorg() {
        return ztuorg;
    }

    /**
     * 设置：库存表-ZTUORG
     *
     * @param ztuorg
     */
    public void setZtuorg(Integer ztuorg) {
        this.ztuorg = ztuorg;
    }

    /**
     * 获取：库存表-ZTLOTN
     *
     * @return ZTLOTN
     */
    public String getZtlotn() {
        return ztlotn;
    }

    /**
     * 设置：库存表-ZTLOTN
     *
     * @param ztlotn
     */
    public void setZtlotn(String ztlotn) {
        this.ztlotn = ztlotn == null ? null : ztlotn.trim();
    }

    /**
     * 获取：库存表-日期
     *
     * @return 日期
     */
    public Date getZtupmj() {
        return ztupmj;
    }

    /**
     * 设置：库存表-日期
     *
     * @param ztupmj 库存表-日期
     */
    public void setZtupmj(Date ztupmj) {
        this.ztupmj = ztupmj;
    }

    /**
     * 获取：库存表-时间
     *
     * @return 时间
     */
    public String getZtupmt() {
        return ztupmt;
    }

    /**
     * 设置：库存表-时间
     *
     * @param ztupmt 库存表-时间
     */
    public void setZtupmt(String ztupmt) {
        this.ztupmt = ztupmt == null ? null : ztupmt.trim();
    }

    /**
     * 获取：库存表-标识
     *
     * @return 标识
     */
    public String getZtflag() {
        return ztflag;
    }

    /**
     * 设置：库存表-标识
     *
     * @param ztflag 库存表-标识
     */
    public void setZtflag(String ztflag) {
        this.ztflag = ztflag == null ? null : ztflag.trim();
    }
}