package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 * f58a5013
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58A5013DO implements Serializable {
    /**
     * f58a5013-ZTVR01
     */
    private String ztvr01;

    /**
     * f58a5013-ZTEDSP
     */
    private String ztedsp;

    /**
     * f58a5013-ZTDL01
     */
    private String ztdl01;

    /**
     * f58a5013-ZTURCD
     */
    private String zturcd;

    /**
     * f58a5013-ZTURDT
     */
    private Date zturdt;

    /**
     * f58a5013-ZTURAT
     */
    private Integer zturat;

    /**
     * f58a5013-ZTURAB
     */
    private Integer zturab;

    /**
     * f58a5013-ZTURRF
     */
    private String zturrf;

    /**
     * f58a5013-ZTPID
     */
    private String ztpid;

    /**
     * f58a5013-ZTUSER
     */
    private String ztuser;

    /**
     * f58a5013-ZTUPMJ
     */
    private Date ztupmj;

    /**
     * f58a5013-ZTUPMT
     */
    private String ztupmt;

    /**
     * f58a5013-ZTJOBN
     */
    private String ztjobn;

    /**
     * f58a5013-ZTFLAG
     */
    private String ztflag;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：f58a5013-ZTVR01
     *
     * @return ZTVR01
     */
    public String getZtvr01() {
        return ztvr01;
    }

    /**
     * 设置：f58a5013-ZTVR01
     *
     * @param ztvr01 f58a5013-ZTVR01
     */
    public void setZtvr01(String ztvr01) {
        this.ztvr01 = ztvr01 == null ? null : ztvr01.trim();
    }

    /**
     * 获取：f58a5013-ZTEDSP
     *
     * @return ZTEDSP
     */
    public String getZtedsp() {
        return ztedsp;
    }

    /**
     * 设置：f58a5013-ZTEDSP
     *
     * @param ztedsp f58a5013-ZTEDSP
     */
    public void setZtedsp(String ztedsp) {
        this.ztedsp = ztedsp == null ? null : ztedsp.trim();
    }

    /**
     * 获取：f58a5013-ZTDL01
     *
     * @return ZTDL01
     */
    public String getZtdl01() {
        return ztdl01;
    }

    /**
     * 设置：f58a5013-ZTDL01
     *
     * @param ztdl01 f58a5013-ZTDL01
     */
    public void setZtdl01(String ztdl01) {
        this.ztdl01 = ztdl01 == null ? null : ztdl01.trim();
    }

    /**
     * 获取：f58a5013-ZTURCD
     *
     * @return ZTURCD
     */
    public String getZturcd() {
        return zturcd;
    }

    /**
     * 设置：f58a5013-ZTURCD
     *
     * @param zturcd f58a5013-ZTURCD
     */
    public void setZturcd(String zturcd) {
        this.zturcd = zturcd == null ? null : zturcd.trim();
    }

    /**
     * 获取：f58a5013-ZTURDT
     *
     * @return ZTURDT
     */
    public Date getZturdt() {
        return zturdt;
    }

    /**
     * 设置：f58a5013-ZTURDT
     *
     * @param zturdt f58a5013-ZTURDT
     */
    public void setZturdt(Date zturdt) {
        this.zturdt = zturdt;
    }

    /**
     * 获取：f58a5013-ZTURAT
     *
     * @return ZTURAT
     */
    public Integer getZturat() {
        return zturat;
    }

    /**
     * 设置：f58a5013-ZTURAT
     *
     * @param zturat f58a5013-ZTURAT
     */
    public void setZturat(Integer zturat) {
        this.zturat = zturat;
    }

    /**
     * 获取：f58a5013-ZTURAB
     *
     * @return ZTURAB
     */
    public Integer getZturab() {
        return zturab;
    }

    /**
     * 设置：f58a5013-ZTURAB
     *
     * @param zturab f58a5013-ZTURAB
     */
    public void setZturab(Integer zturab) {
        this.zturab = zturab;
    }

    /**
     * 获取：f58a5013-ZTURRF
     *
     * @return ZTURRF
     */
    public String getZturrf() {
        return zturrf;
    }

    /**
     * 设置：f58a5013-ZTURRF
     *
     * @param zturrf f58a5013-ZTURRF
     */
    public void setZturrf(String zturrf) {
        this.zturrf = zturrf == null ? null : zturrf.trim();
    }

    /**
     * 获取：f58a5013-ZTPID
     *
     * @return ZTPID
     */
    public String getZtpid() {
        return ztpid;
    }

    /**
     * 设置：f58a5013-ZTPID
     *
     * @param ztpid f58a5013-ZTPID
     */
    public void setZtpid(String ztpid) {
        this.ztpid = ztpid == null ? null : ztpid.trim();
    }

    /**
     * 获取：f58a5013-ZTUSER
     *
     * @return ZTUSER
     */
    public String getZtuser() {
        return ztuser;
    }

    /**
     * 设置：f58a5013-ZTUSER
     *
     * @param ztuser f58a5013-ZTUSER
     */
    public void setZtuser(String ztuser) {
        this.ztuser = ztuser == null ? null : ztuser.trim();
    }

    /**
     * 获取：f58a5013-ZTUPMJ
     *
     * @return ZTUPMJ
     */
    public Date getZtupmj() {
        return ztupmj;
    }

    /**
     * 设置：f58a5013-ZTUPMJ
     *
     * @param ztupmj f58a5013-ZTUPMJ
     */
    public void setZtupmj(Date ztupmj) {
        this.ztupmj = ztupmj;
    }

    /**
     * 获取：f58a5013-ZTUPMT
     *
     * @return ZTUPMT
     */
    public String getZtupmt() {
        return ztupmt;
    }

    /**
     * 设置：f58a5013-ZTUPMT
     *
     * @param ztupmt f58a5013-ZTUPMT
     */
    public void setZtupmt(String ztupmt) {
        this.ztupmt = ztupmt == null ? null : ztupmt.trim();
    }

    /**
     * 获取：f58a5013-ZTJOBN
     *
     * @return ZTJOBN
     */
    public String getZtjobn() {
        return ztjobn;
    }

    /**
     * 设置：f58a5013-ZTJOBN
     *
     * @param ztjobn f58a5013-ZTJOBN
     */
    public void setZtjobn(String ztjobn) {
        this.ztjobn = ztjobn == null ? null : ztjobn.trim();
    }

    /**
     * 获取：f58a5013-ZTFLAG
     *
     * @return ZTFLAG
     */
    public String getZtflag() {
        return ztflag;
    }

    /**
     * 设置：f58a5013-ZTFLAG
     *
     * @param ztflag f58a5013-ZTFLAG
     */
    public void setZtflag(String ztflag) {
        this.ztflag = ztflag == null ? null : ztflag.trim();
    }
}