package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * ASN单
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58A4710DO implements Serializable {
    /**
     * ASN单-CKKCOO
     */
    private String ckkcoo;

    /**
     * ASN单-CKDOCO
     */
    private Integer ckdoco;

    /**
     * ASN单-CKDCTO
     */
    private String ckdcto;

    /**
     * ASN单-CKLNID
     */
    private BigDecimal cklnid;

    /**
     * ASN单-CKMMCU
     */
    private String ckmmcu;

    /**
     * ASN单-CKMCU
     */
    private String ckmcu;

    /**
     * ASN单-CKSHAN
     */
    private Integer ckshan;

    /**
     * ASN单-CKVR01
     */
    private String ckvr01;

    /**
     * ASN单-CKRKCO
     */
    private String ckrkco;

    /**
     * ASN单-CKRORN
     */
    private String ckrorn;

    /**
     * ASN单-CKRCTO
     */
    private String ckrcto;

    /**
     * ASN单-CKRLLN
     */
    private BigDecimal ckrlln;

    /**
     * ASN单-CKLITM
     */
    private String cklitm;

    /**
     * ASN单-CKUORG
     */
    private BigDecimal ckuorg;

    /**
     * ASN单-CKUOM1
     */
    private String ckuom1;

    /**
     * ASN单-CKSOQS
     */
    private BigDecimal cksoqs;

    /**
     * ASN单-CKUOM6
     */
    private String ckuom6;

    /**
     * ASN单-CKTRDJ
     */
    private Date cktrdj;

    /**
     * ASN单-CKADDJ
     */
    private Date ckaddj;

    /**
     * ASN单-CKE58DDRQ
     */
    private String cke58ddrq;

    /**
     * ASN单-CKE58FYRQ
     */
    private String cke58fyrq;

    /**
     * ASN单-CKLOCN
     */
    private String cklocn;

    /**
     * ASN单-CKLOTN
     */
    private String cklotn;

    /**
     * ASN单-CKU4DJ
     */
    private Date cku4dj;

    /**
     * ASN单-CKMMEJ
     */
    private Date ckmmej;

    /**
     * ASN单-CKURCD
     */
    private String ckurcd;

    /**
     * ASN单-CKURDT
     */
    private Date ckurdt;

    /**
     * ASN单-CKURAT
     */
    private BigDecimal ckurat;

    /**
     * ASN单-CKURAB
     */
    private Integer ckurab;

    /**
     * ASN单-CKURRF
     */
    private String ckurrf;

    /**
     * ASN单-CKEV01
     */
    private String ckev01;

    /**
     * ASN单-CKEV02
     */
    private String ckev02;

    /**
     * ASN单-CKEV03
     */
    private String ckev03;

    /**
     * ASN单-CKUSER
     */
    private String ckuser;

    /**
     * ASN单-CKPID
     */
    private String ckpid;

    /**
     * ASN单-CKJOBN
     */
    private String ckjobn;

    /**
     * ASN单-CKUPMJ
     */
    private Date ckupmj;

    /**
     * ASN单-CKUPMT
     */
    private Date ckupmt;

    /**
     * ASN单-CKUPRC
     */
    private BigDecimal ckuprc;

    /**
     * ASN单-CKAEXP
     */
    private BigDecimal ckaexp;

    /**
     * ASN单-CKAN8
     */
    private Integer ckan8;

    /**
     * ASN单-CKINDATE
     */
    private Date ckindate;

    /**
     * ASN单-CKINRMK
     */
    private String ckinrmk;

    /**
     * ASN单-CKREDATE
     */
    private Date ckredate;

    /**
     * ASN单-CKRERMK
     */
    private String ckrermk;

    /**
     * ASN单-CKUKID
     */
    private Integer ckukid;

    /**
     * ASN单-CKSTATUS
     */
    private String ckstatus;

    /**
     * ASN单-CKFLAG
     */
    private String ckflag;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：ASN单-CKKCOO
     *
     * @return CKKCOO
     */
    public String getCkkcoo() {
        return ckkcoo;
    }

    /**
     * 设置：ASN单-CKKCOO
     *
     * @param ckkcoo
     */
    public void setCkkcoo(String ckkcoo) {
        this.ckkcoo = ckkcoo == null ? null : ckkcoo.trim();
    }

    /**
     * 获取：ASN单-CKDOCO
     *
     * @return CKDOCO
     */
    public Integer getCkdoco() {
        return ckdoco;
    }

    /**
     * 设置：ASN单-CKDOCO
     *
     * @param ckdoco
     */
    public void setCkdoco(Integer ckdoco) {
        this.ckdoco = ckdoco;
    }

    /**
     * 获取：ASN单-CKDCTO
     *
     * @return CKDCTO
     */
    public String getCkdcto() {
        return ckdcto;
    }

    /**
     * 设置：ASN单-CKDCTO
     *
     * @param ckdcto
     */
    public void setCkdcto(String ckdcto) {
        this.ckdcto = ckdcto == null ? null : ckdcto.trim();
    }

    /**
     * 获取：ASN单-CKLNID
     *
     * @return CKLNID
     */
    public BigDecimal getCklnid() {
        return cklnid;
    }

    /**
     * 设置：ASN单-CKLNID
     *
     * @param cklnid
     */
    public void setCklnid(BigDecimal cklnid) {
        this.cklnid = cklnid;
    }

    /**
     * 获取：ASN单-CKMMCU
     *
     * @return CKMMCU
     */
    public String getCkmmcu() {
        return ckmmcu;
    }

    /**
     * 设置：ASN单-CKMMCU
     *
     * @param ckmmcu
     */
    public void setCkmmcu(String ckmmcu) {
        this.ckmmcu = ckmmcu == null ? null : ckmmcu.trim();
    }

    /**
     * 获取：ASN单-CKMCU
     *
     * @return CKMCU
     */
    public String getCkmcu() {
        return ckmcu;
    }

    /**
     * 设置：ASN单-CKMCU
     *
     * @param ckmcu
     */
    public void setCkmcu(String ckmcu) {
        this.ckmcu = ckmcu == null ? null : ckmcu.trim();
    }

    /**
     * 获取：ASN单-CKSHAN
     *
     * @return CKSHAN
     */
    public Integer getCkshan() {
        return ckshan;
    }

    /**
     * 设置：ASN单-CKSHAN
     *
     * @param ckshan
     */
    public void setCkshan(Integer ckshan) {
        this.ckshan = ckshan;
    }

    /**
     * 获取：ASN单-CKVR01
     *
     * @return CKVR01
     */
    public String getCkvr01() {
        return ckvr01;
    }

    /**
     * 设置：ASN单-CKVR01
     *
     * @param ckvr01
     */
    public void setCkvr01(String ckvr01) {
        this.ckvr01 = ckvr01 == null ? null : ckvr01.trim();
    }

    /**
     * 获取：ASN单-CKRKCO
     *
     * @return CKRKCO
     */
    public String getCkrkco() {
        return ckrkco;
    }

    /**
     * 设置：ASN单-CKRKCO
     *
     * @param ckrkco
     */
    public void setCkrkco(String ckrkco) {
        this.ckrkco = ckrkco == null ? null : ckrkco.trim();
    }

    /**
     * 获取：ASN单-CKRORN
     *
     * @return CKRORN
     */
    public String getCkrorn() {
        return ckrorn;
    }

    /**
     * 设置：ASN单-CKRORN
     *
     * @param ckrorn
     */
    public void setCkrorn(String ckrorn) {
        this.ckrorn = ckrorn == null ? null : ckrorn.trim();
    }

    /**
     * 获取：ASN单-CKRCTO
     *
     * @return CKRCTO
     */
    public String getCkrcto() {
        return ckrcto;
    }

    /**
     * 设置：ASN单-CKRCTO
     *
     * @param ckrcto
     */
    public void setCkrcto(String ckrcto) {
        this.ckrcto = ckrcto == null ? null : ckrcto.trim();
    }

    /**
     * 获取：ASN单-CKRLLN
     *
     * @return CKRLLN
     */
    public BigDecimal getCkrlln() {
        return ckrlln;
    }

    /**
     * 设置：ASN单-CKRLLN
     *
     * @param ckrlln
     */
    public void setCkrlln(BigDecimal ckrlln) {
        this.ckrlln = ckrlln;
    }

    /**
     * 获取：ASN单-CKLITM
     *
     * @return CKLITM
     */
    public String getCklitm() {
        return cklitm;
    }

    /**
     * 设置：ASN单-CKLITM
     *
     * @param cklitm
     */
    public void setCklitm(String cklitm) {
        this.cklitm = cklitm == null ? null : cklitm.trim();
    }

    /**
     * 获取：ASN单-CKUORG
     *
     * @return CKUORG
     */
    public BigDecimal getCkuorg() {
        return ckuorg;
    }

    /**
     * 设置：ASN单-CKUORG
     *
     * @param ckuorg
     */
    public void setCkuorg(BigDecimal ckuorg) {
        this.ckuorg = ckuorg;
    }

    /**
     * 获取：ASN单-CKUOM1
     *
     * @return CKUOM1
     */
    public String getCkuom1() {
        return ckuom1;
    }

    /**
     * 设置：ASN单-CKUOM1
     *
     * @param ckuom1
     */
    public void setCkuom1(String ckuom1) {
        this.ckuom1 = ckuom1 == null ? null : ckuom1.trim();
    }

    /**
     * 获取：ASN单-CKSOQS
     *
     * @return CKSOQS
     */
    public BigDecimal getCksoqs() {
        return cksoqs;
    }

    /**
     * 设置：ASN单-CKSOQS
     *
     * @param cksoqs
     */
    public void setCksoqs(BigDecimal cksoqs) {
        this.cksoqs = cksoqs;
    }

    /**
     * 获取：ASN单-CKUOM6
     *
     * @return CKUOM6
     */
    public String getCkuom6() {
        return ckuom6;
    }

    /**
     * 设置：ASN单-CKUOM6
     *
     * @param ckuom6
     */
    public void setCkuom6(String ckuom6) {
        this.ckuom6 = ckuom6 == null ? null : ckuom6.trim();
    }

    /**
     * 获取：ASN单-CKTRDJ
     *
     * @return CKTRDJ
     */
    public Date getCktrdj() {
        return cktrdj;
    }

    /**
     * 设置：ASN单-CKTRDJ
     *
     * @param cktrdj
     */
    public void setCktrdj(Date cktrdj) {
        this.cktrdj = cktrdj;
    }

    /**
     * 获取：ASN单-CKADDJ
     *
     * @return CKADDJ
     */
    public Date getCkaddj() {
        return ckaddj;
    }

    /**
     * 设置：ASN单-CKADDJ
     *
     * @param ckaddj
     */
    public void setCkaddj(Date ckaddj) {
        this.ckaddj = ckaddj;
    }

    /**
     * 获取：ASN单-CKE58DDRQ
     *
     * @return CKE58DDRQ
     */
    public String getCke58ddrq() {
        return cke58ddrq;
    }

    /**
     * 设置：ASN单-CKE58DDRQ
     *
     * @param cke58ddrq
     */
    public void setCke58ddrq(String cke58ddrq) {
        this.cke58ddrq = cke58ddrq == null ? null : cke58ddrq.trim();
    }

    /**
     * 获取：ASN单-CKE58FYRQ
     *
     * @return CKE58FYRQ
     */
    public String getCke58fyrq() {
        return cke58fyrq;
    }

    /**
     * 设置：ASN单-CKE58FYRQ
     *
     * @param cke58fyrq
     */
    public void setCke58fyrq(String cke58fyrq) {
        this.cke58fyrq = cke58fyrq == null ? null : cke58fyrq.trim();
    }

    /**
     * 获取：ASN单-CKLOCN
     *
     * @return CKLOCN
     */
    public String getCklocn() {
        return cklocn;
    }

    /**
     * 设置：ASN单-CKLOCN
     *
     * @param cklocn
     */
    public void setCklocn(String cklocn) {
        this.cklocn = cklocn == null ? null : cklocn.trim();
    }

    /**
     * 获取：ASN单-CKLOTN
     *
     * @return CKLOTN
     */
    public String getCklotn() {
        return cklotn;
    }

    /**
     * 设置：ASN单-CKLOTN
     *
     * @param cklotn
     */
    public void setCklotn(String cklotn) {
        this.cklotn = cklotn == null ? null : cklotn.trim();
    }

    /**
     * 获取：ASN单-CKU4DJ
     *
     * @return CKU4DJ
     */
    public Date getCku4dj() {
        return cku4dj;
    }

    /**
     * 设置：ASN单-CKU4DJ
     *
     * @param cku4dj
     */
    public void setCku4dj(Date cku4dj) {
        this.cku4dj = cku4dj;
    }

    /**
     * 获取：ASN单-CKMMEJ
     *
     * @return CKMMEJ
     */
    public Date getCkmmej() {
        return ckmmej;
    }

    /**
     * 设置：ASN单-CKMMEJ
     *
     * @param ckmmej
     */
    public void setCkmmej(Date ckmmej) {
        this.ckmmej = ckmmej;
    }

    /**
     * 获取：ASN单-CKURCD
     *
     * @return CKURCD
     */
    public String getCkurcd() {
        return ckurcd;
    }

    /**
     * 设置：ASN单-CKURCD
     *
     * @param ckurcd
     */
    public void setCkurcd(String ckurcd) {
        this.ckurcd = ckurcd == null ? null : ckurcd.trim();
    }

    /**
     * 获取：ASN单-CKURDT
     *
     * @return CKURDT
     */
    public Date getCkurdt() {
        return ckurdt;
    }

    /**
     * 设置：ASN单-CKURDT
     *
     * @param ckurdt
     */
    public void setCkurdt(Date ckurdt) {
        this.ckurdt = ckurdt;
    }

    /**
     * 获取：ASN单-CKURAT
     *
     * @return CKURAT
     */
    public BigDecimal getCkurat() {
        return ckurat;
    }

    /**
     * 设置：ASN单-CKURAT
     *
     * @param ckurat
     */
    public void setCkurat(BigDecimal ckurat) {
        this.ckurat = ckurat;
    }

    /**
     * 获取：ASN单-CKURAB
     *
     * @return CKURAB
     */
    public Integer getCkurab() {
        return ckurab;
    }

    /**
     * 设置：ASN单-CKURAB
     *
     * @param ckurab
     */
    public void setCkurab(Integer ckurab) {
        this.ckurab = ckurab;
    }

    /**
     * 获取：ASN单-CKURRF
     *
     * @return CKURRF
     */
    public String getCkurrf() {
        return ckurrf;
    }

    /**
     * 设置：ASN单-CKURRF
     *
     * @param ckurrf
     */
    public void setCkurrf(String ckurrf) {
        this.ckurrf = ckurrf == null ? null : ckurrf.trim();
    }

    /**
     * 获取：ASN单-CKEV01
     *
     * @return CKEV01
     */
    public String getCkev01() {
        return ckev01;
    }

    /**
     * 设置：ASN单-CKEV01
     *
     * @param ckev01
     */
    public void setCkev01(String ckev01) {
        this.ckev01 = ckev01 == null ? null : ckev01.trim();
    }

    /**
     * 获取：ASN单-CKEV02
     *
     * @return CKEV02
     */
    public String getCkev02() {
        return ckev02;
    }

    /**
     * 设置：ASN单-CKEV02
     *
     * @param ckev02
     */
    public void setCkev02(String ckev02) {
        this.ckev02 = ckev02 == null ? null : ckev02.trim();
    }

    /**
     * 获取：ASN单-CKEV03
     *
     * @return CKEV03
     */
    public String getCkev03() {
        return ckev03;
    }

    /**
     * 设置：ASN单-CKEV03
     *
     * @param ckev03
     */
    public void setCkev03(String ckev03) {
        this.ckev03 = ckev03 == null ? null : ckev03.trim();
    }

    /**
     * 获取：ASN单-CKUSER
     *
     * @return CKUSER
     */
    public String getCkuser() {
        return ckuser;
    }

    /**
     * 设置：ASN单-CKUSER
     *
     * @param ckuser
     */
    public void setCkuser(String ckuser) {
        this.ckuser = ckuser == null ? null : ckuser.trim();
    }

    /**
     * 获取：ASN单-CKPID
     *
     * @return CKPID
     */
    public String getCkpid() {
        return ckpid;
    }

    /**
     * 设置：ASN单-CKPID
     *
     * @param ckpid
     */
    public void setCkpid(String ckpid) {
        this.ckpid = ckpid == null ? null : ckpid.trim();
    }

    /**
     * 获取：ASN单-CKJOBN
     *
     * @return CKJOBN
     */
    public String getCkjobn() {
        return ckjobn;
    }

    /**
     * 设置：ASN单-CKJOBN
     *
     * @param ckjobn
     */
    public void setCkjobn(String ckjobn) {
        this.ckjobn = ckjobn == null ? null : ckjobn.trim();
    }

    /**
     * 获取：ASN单-CKUPMJ
     *
     * @return CKUPMJ
     */
    public Date getCkupmj() {
        return ckupmj;
    }

    /**
     * 设置：ASN单-CKUPMJ
     *
     * @param ckupmj
     */
    public void setCkupmj(Date ckupmj) {
        this.ckupmj = ckupmj;
    }

    /**
     * 获取：ASN单-CKUPMT
     *
     * @return CKUPMT
     */
    public Date getCkupmt() {
        return ckupmt;
    }

    /**
     * 设置：ASN单-CKUPMT
     *
     * @param ckupmt
     */
    public void setCkupmt(Date ckupmt) {
        this.ckupmt = ckupmt;
    }

    /**
     * 获取：ASN单-CKUPRC
     *
     * @return CKUPRC
     */
    public BigDecimal getCkuprc() {
        return ckuprc;
    }

    /**
     * 设置：ASN单-CKUPRC
     *
     * @param ckuprc
     */
    public void setCkuprc(BigDecimal ckuprc) {
        this.ckuprc = ckuprc;
    }

    /**
     * 获取：ASN单-CKAEXP
     *
     * @return CKAEXP
     */
    public BigDecimal getCkaexp() {
        return ckaexp;
    }

    /**
     * 设置：ASN单-CKAEXP
     *
     * @param ckaexp
     */
    public void setCkaexp(BigDecimal ckaexp) {
        this.ckaexp = ckaexp;
    }

    /**
     * 获取：ASN单-CKAN8
     *
     * @return CKAN8
     */
    public Integer getCkan8() {
        return ckan8;
    }

    /**
     * 设置：ASN单-CKAN8
     *
     * @param ckan8
     */
    public void setCkan8(Integer ckan8) {
        this.ckan8 = ckan8;
    }

    /**
     * 获取：ASN单-CKINDATE
     *
     * @return CKINDATE
     */
    public Date getCkindate() {
        return ckindate;
    }

    /**
     * 设置：ASN单-CKINDATE
     *
     * @param ckindate
     */
    public void setCkindate(Date ckindate) {
        this.ckindate = ckindate;
    }

    /**
     * 获取：ASN单-CKINRMK
     *
     * @return CKINRMK
     */
    public String getCkinrmk() {
        return ckinrmk;
    }

    /**
     * 设置：ASN单-CKINRMK
     *
     * @param ckinrmk
     */
    public void setCkinrmk(String ckinrmk) {
        this.ckinrmk = ckinrmk == null ? null : ckinrmk.trim();
    }

    /**
     * 获取：ASN单-CKREDATE
     *
     * @return CKREDATE
     */
    public Date getCkredate() {
        return ckredate;
    }

    /**
     * 设置：ASN单-CKREDATE
     *
     * @param ckredate
     */
    public void setCkredate(Date ckredate) {
        this.ckredate = ckredate;
    }

    /**
     * 获取：ASN单-CKRERMK
     *
     * @return CKRERMK
     */
    public String getCkrermk() {
        return ckrermk;
    }

    /**
     * 设置：ASN单-CKRERMK
     *
     * @param ckrermk
     */
    public void setCkrermk(String ckrermk) {
        this.ckrermk = ckrermk == null ? null : ckrermk.trim();
    }

    /**
     * 获取：ASN单-CKUKID
     *
     * @return CKUKID
     */
    public Integer getCkukid() {
        return ckukid;
    }

    /**
     * 设置：ASN单-CKUKID
     *
     * @param ckukid
     */
    public void setCkukid(Integer ckukid) {
        this.ckukid = ckukid;
    }

    /**
     * 获取：ASN单-CKSTATUS
     *
     * @return CKSTATUS
     */
    public String getCkstatus() {
        return ckstatus;
    }

    /**
     * 设置：ASN单-CKSTATUS
     *
     * @param ckstatus
     */
    public void setCkstatus(String ckstatus) {
        this.ckstatus = ckstatus == null ? null : ckstatus.trim();
    }

    /**
     * 获取：ASN单-CKFLAG
     *
     * @return CKFLAG
     */
    public String getCkflag() {
        return ckflag;
    }

    /**
     * 设置：ASN单-CKFLAG
     *
     * @param ckflag
     */
    public void setCkflag(String ckflag) {
        this.ckflag = ckflag == null ? null : ckflag.trim();
    }
}