package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 * f58k0101
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58K0101DO implements Serializable {
    /**
     * f58k0101-MKAN8
     */
    private Integer mkan8;

    /**
     * f58k0101-MKALPH
     */
    private String mkalph;

    /**
     * f58k0101-MKAT1
     */
    private String mkat1;

    /**
     * f58k0101-MKMCU
     */
    private String mkmcu;

    /**
     * f58k0101-MKMLNM
     */
    private String mkmlnm;

    /**
     * f58k0101-MKADD1
     */
    private String mkadd1;

    /**
     * f58k0101-MKADD2
     */
    private String mkadd2;

    /**
     * f58k0101-MKADD3
     */
    private String mkadd3;

    /**
     * f58k0101-MKADD4
     */
    private String mkadd4;

    /**
     * f58k0101-MKCTY1
     */
    private String mkcty1;

    /**
     * f58k0101-MKADDS
     */
    private String mkadds;

    /**
     * f58k0101-MKADDZ
     */
    private String mkaddz;

    /**
     * f58k0101-MKCTR
     */
    private String mkctr;

    /**
     * f58k0101-MKCOUN
     */
    private String mkcoun;

    /**
     * f58k0101-MKYEARSTAR
     */
    private String mkyearstar;

    /**
     * f58k0101-MKREVRNG
     */
    private String mkrevrng;

    /**
     * f58k0101-MKDSC1
     */
    private String mkdsc1;

    /**
     * f58k0101-MKGROWTHR
     */
    private String mkgrowthr;

    /**
     * f58k0101-MKPA8
     */
    private String mkpa8;

    /**
     * f58k0101-MKAN84
     */
    private String mkan84;

    /**
     * f58k0101-MKAN86
     */
    private String mkan86;

    /**
     * f58k0101-MKAC01
     */
    private String mkac01;

    /**
     * f58k0101-MKDL01
     */
    private String mkdl01;

    /**
     * f58k0101-MKAC02
     */
    private String mkac02;

    /**
     * f58k0101-MKDL02
     */
    private String mkdl02;

    /**
     * f58k0101-MKAC03
     */
    private String mkac03;

    /**
     * f58k0101-MKDL03
     */
    private String mkdl03;

    /**
     * f58k0101-MKAC04
     */
    private String mkac04;

    /**
     * f58k0101-MKDL04
     */
    private String mkdl04;

    /**
     * f58k0101-MKAC05
     */
    private String mkac05;

    /**
     * f58k0101-MKDL05
     */
    private String mkdl05;

    /**
     * f58k0101-MKAC06
     */
    private String mkac06;

    /**
     * f58k0101-MKDL06
     */
    private String mkdl06;

    /**
     * f58k0101-MKAC07
     */
    private String mkac07;

    /**
     * f58k0101-MKDL07
     */
    private String mkdl07;

    /**
     * f58k0101-MKAC08
     */
    private String mkac08;

    /**
     * f58k0101-MKDL08
     */
    private String mkdl08;

    /**
     * f58k0101-MKUSER
     */
    private String mkuser;

    /**
     * f58k0101-MKPID
     */
    private String mkpid;

    /**
     * f58k0101-MKJOBN
     */
    private String mkjobn;

    /**
     * f58k0101-MKUPMJ
     */
    private Date mkupmj;

    /**
     * f58k0101-MKUPMT
     */
    private String mkupmt;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：f58k0101-MKAN8
     *
     * @return MKAN8
     */
    public Integer getMkan8() {
        return mkan8;
    }

    /**
     * 设置：f58k0101-MKAN8
     *
     * @param mkan8 f58k0101-MKAN8
     */
    public void setMkan8(Integer mkan8) {
        this.mkan8 = mkan8;
    }

    /**
     * 获取：f58k0101-MKALPH
     *
     * @return MKALPH
     */
    public String getMkalph() {
        return mkalph;
    }

    /**
     * 设置：f58k0101-MKALPH
     *
     * @param mkalph f58k0101-MKALPH
     */
    public void setMkalph(String mkalph) {
        this.mkalph = mkalph == null ? null : mkalph.trim();
    }

    /**
     * 获取：f58k0101-MKAT1
     *
     * @return MKAT1
     */
    public String getMkat1() {
        return mkat1;
    }

    /**
     * 设置：f58k0101-MKAT1
     *
     * @param mkat1 f58k0101-MKAT1
     */
    public void setMkat1(String mkat1) {
        this.mkat1 = mkat1 == null ? null : mkat1.trim();
    }

    /**
     * 获取：f58k0101-MKMCU
     *
     * @return MKMCU
     */
    public String getMkmcu() {
        return mkmcu;
    }

    /**
     * 设置：f58k0101-MKMCU
     *
     * @param mkmcu f58k0101-MKMCU
     */
    public void setMkmcu(String mkmcu) {
        this.mkmcu = mkmcu == null ? null : mkmcu.trim();
    }

    /**
     * 获取：f58k0101-MKMLNM
     *
     * @return MKMLNM
     */
    public String getMkmlnm() {
        return mkmlnm;
    }

    /**
     * 设置：f58k0101-MKMLNM
     *
     * @param mkmlnm f58k0101-MKMLNM
     */
    public void setMkmlnm(String mkmlnm) {
        this.mkmlnm = mkmlnm == null ? null : mkmlnm.trim();
    }

    /**
     * 获取：f58k0101-MKADD1
     *
     * @return MKADD1
     */
    public String getMkadd1() {
        return mkadd1;
    }

    /**
     * 设置：f58k0101-MKADD1
     *
     * @param mkadd1 f58k0101-MKADD1
     */
    public void setMkadd1(String mkadd1) {
        this.mkadd1 = mkadd1 == null ? null : mkadd1.trim();
    }

    /**
     * 获取：f58k0101-MKADD2
     *
     * @return MKADD2
     */
    public String getMkadd2() {
        return mkadd2;
    }

    /**
     * 设置：f58k0101-MKADD2
     *
     * @param mkadd2 f58k0101-MKADD2
     */
    public void setMkadd2(String mkadd2) {
        this.mkadd2 = mkadd2 == null ? null : mkadd2.trim();
    }

    /**
     * 获取：f58k0101-MKADD3
     *
     * @return MKADD3
     */
    public String getMkadd3() {
        return mkadd3;
    }

    /**
     * 设置：f58k0101-MKADD3
     *
     * @param mkadd3 f58k0101-MKADD3
     */
    public void setMkadd3(String mkadd3) {
        this.mkadd3 = mkadd3 == null ? null : mkadd3.trim();
    }

    /**
     * 获取：f58k0101-MKADD4
     *
     * @return MKADD4
     */
    public String getMkadd4() {
        return mkadd4;
    }

    /**
     * 设置：f58k0101-MKADD4
     *
     * @param mkadd4 f58k0101-MKADD4
     */
    public void setMkadd4(String mkadd4) {
        this.mkadd4 = mkadd4 == null ? null : mkadd4.trim();
    }

    /**
     * 获取：f58k0101-MKCTY1
     *
     * @return MKCTY1
     */
    public String getMkcty1() {
        return mkcty1;
    }

    /**
     * 设置：f58k0101-MKCTY1
     *
     * @param mkcty1 f58k0101-MKCTY1
     */
    public void setMkcty1(String mkcty1) {
        this.mkcty1 = mkcty1 == null ? null : mkcty1.trim();
    }

    /**
     * 获取：f58k0101-MKADDS
     *
     * @return MKADDS
     */
    public String getMkadds() {
        return mkadds;
    }

    /**
     * 设置：f58k0101-MKADDS
     *
     * @param mkadds f58k0101-MKADDS
     */
    public void setMkadds(String mkadds) {
        this.mkadds = mkadds == null ? null : mkadds.trim();
    }

    /**
     * 获取：f58k0101-MKADDZ
     *
     * @return MKADDZ
     */
    public String getMkaddz() {
        return mkaddz;
    }

    /**
     * 设置：f58k0101-MKADDZ
     *
     * @param mkaddz f58k0101-MKADDZ
     */
    public void setMkaddz(String mkaddz) {
        this.mkaddz = mkaddz == null ? null : mkaddz.trim();
    }

    /**
     * 获取：f58k0101-MKCTR
     *
     * @return MKCTR
     */
    public String getMkctr() {
        return mkctr;
    }

    /**
     * 设置：f58k0101-MKCTR
     *
     * @param mkctr f58k0101-MKCTR
     */
    public void setMkctr(String mkctr) {
        this.mkctr = mkctr == null ? null : mkctr.trim();
    }

    /**
     * 获取：f58k0101-MKCOUN
     *
     * @return MKCOUN
     */
    public String getMkcoun() {
        return mkcoun;
    }

    /**
     * 设置：f58k0101-MKCOUN
     *
     * @param mkcoun f58k0101-MKCOUN
     */
    public void setMkcoun(String mkcoun) {
        this.mkcoun = mkcoun == null ? null : mkcoun.trim();
    }

    /**
     * 获取：f58k0101-MKYEARSTAR
     *
     * @return MKYEARSTAR
     */
    public String getMkyearstar() {
        return mkyearstar;
    }

    /**
     * 设置：f58k0101-MKYEARSTAR
     *
     * @param mkyearstar f58k0101-MKYEARSTAR
     */
    public void setMkyearstar(String mkyearstar) {
        this.mkyearstar = mkyearstar == null ? null : mkyearstar.trim();
    }

    /**
     * 获取：f58k0101-MKREVRNG
     *
     * @return MKREVRNG
     */
    public String getMkrevrng() {
        return mkrevrng;
    }

    /**
     * 设置：f58k0101-MKREVRNG
     *
     * @param mkrevrng f58k0101-MKREVRNG
     */
    public void setMkrevrng(String mkrevrng) {
        this.mkrevrng = mkrevrng == null ? null : mkrevrng.trim();
    }

    /**
     * 获取：f58k0101-MKDSC1
     *
     * @return MKDSC1
     */
    public String getMkdsc1() {
        return mkdsc1;
    }

    /**
     * 设置：f58k0101-MKDSC1
     *
     * @param mkdsc1 f58k0101-MKDSC1
     */
    public void setMkdsc1(String mkdsc1) {
        this.mkdsc1 = mkdsc1 == null ? null : mkdsc1.trim();
    }

    /**
     * 获取：f58k0101-MKGROWTHR
     *
     * @return MKGROWTHR
     */
    public String getMkgrowthr() {
        return mkgrowthr;
    }

    /**
     * 设置：f58k0101-MKGROWTHR
     *
     * @param mkgrowthr f58k0101-MKGROWTHR
     */
    public void setMkgrowthr(String mkgrowthr) {
        this.mkgrowthr = mkgrowthr == null ? null : mkgrowthr.trim();
    }

    /**
     * 获取：f58k0101-MKPA8
     *
     * @return MKPA8
     */
    public String getMkpa8() {
        return mkpa8;
    }

    /**
     * 设置：f58k0101-MKPA8
     *
     * @param mkpa8 f58k0101-MKPA8
     */
    public void setMkpa8(String mkpa8) {
        this.mkpa8 = mkpa8 == null ? null : mkpa8.trim();
    }

    /**
     * 获取：f58k0101-MKAN84
     *
     * @return MKAN84
     */
    public String getMkan84() {
        return mkan84;
    }

    /**
     * 设置：f58k0101-MKAN84
     *
     * @param mkan84 f58k0101-MKAN84
     */
    public void setMkan84(String mkan84) {
        this.mkan84 = mkan84 == null ? null : mkan84.trim();
    }

    /**
     * 获取：f58k0101-MKAN86
     *
     * @return MKAN86
     */
    public String getMkan86() {
        return mkan86;
    }

    /**
     * 设置：f58k0101-MKAN86
     *
     * @param mkan86 f58k0101-MKAN86
     */
    public void setMkan86(String mkan86) {
        this.mkan86 = mkan86 == null ? null : mkan86.trim();
    }

    /**
     * 获取：f58k0101-MKAC01
     *
     * @return MKAC01
     */
    public String getMkac01() {
        return mkac01;
    }

    /**
     * 设置：f58k0101-MKAC01
     *
     * @param mkac01 f58k0101-MKAC01
     */
    public void setMkac01(String mkac01) {
        this.mkac01 = mkac01 == null ? null : mkac01.trim();
    }

    /**
     * 获取：f58k0101-MKDL01
     *
     * @return MKDL01
     */
    public String getMkdl01() {
        return mkdl01;
    }

    /**
     * 设置：f58k0101-MKDL01
     *
     * @param mkdl01 f58k0101-MKDL01
     */
    public void setMkdl01(String mkdl01) {
        this.mkdl01 = mkdl01 == null ? null : mkdl01.trim();
    }

    /**
     * 获取：f58k0101-MKAC02
     *
     * @return MKAC02
     */
    public String getMkac02() {
        return mkac02;
    }

    /**
     * 设置：f58k0101-MKAC02
     *
     * @param mkac02 f58k0101-MKAC02
     */
    public void setMkac02(String mkac02) {
        this.mkac02 = mkac02 == null ? null : mkac02.trim();
    }

    /**
     * 获取：f58k0101-MKDL02
     *
     * @return MKDL02
     */
    public String getMkdl02() {
        return mkdl02;
    }

    /**
     * 设置：f58k0101-MKDL02
     *
     * @param mkdl02 f58k0101-MKDL02
     */
    public void setMkdl02(String mkdl02) {
        this.mkdl02 = mkdl02 == null ? null : mkdl02.trim();
    }

    /**
     * 获取：f58k0101-MKAC03
     *
     * @return MKAC03
     */
    public String getMkac03() {
        return mkac03;
    }

    /**
     * 设置：f58k0101-MKAC03
     *
     * @param mkac03 f58k0101-MKAC03
     */
    public void setMkac03(String mkac03) {
        this.mkac03 = mkac03 == null ? null : mkac03.trim();
    }

    /**
     * 获取：f58k0101-MKDL03
     *
     * @return MKDL03
     */
    public String getMkdl03() {
        return mkdl03;
    }

    /**
     * 设置：f58k0101-MKDL03
     *
     * @param mkdl03 f58k0101-MKDL03
     */
    public void setMkdl03(String mkdl03) {
        this.mkdl03 = mkdl03 == null ? null : mkdl03.trim();
    }

    /**
     * 获取：f58k0101-MKAC04
     *
     * @return MKAC04
     */
    public String getMkac04() {
        return mkac04;
    }

    /**
     * 设置：f58k0101-MKAC04
     *
     * @param mkac04 f58k0101-MKAC04
     */
    public void setMkac04(String mkac04) {
        this.mkac04 = mkac04 == null ? null : mkac04.trim();
    }

    /**
     * 获取：f58k0101-MKDL04
     *
     * @return MKDL04
     */
    public String getMkdl04() {
        return mkdl04;
    }

    /**
     * 设置：f58k0101-MKDL04
     *
     * @param mkdl04 f58k0101-MKDL04
     */
    public void setMkdl04(String mkdl04) {
        this.mkdl04 = mkdl04 == null ? null : mkdl04.trim();
    }

    /**
     * 获取：f58k0101-MKAC05
     *
     * @return MKAC05
     */
    public String getMkac05() {
        return mkac05;
    }

    /**
     * 设置：f58k0101-MKAC05
     *
     * @param mkac05 f58k0101-MKAC05
     */
    public void setMkac05(String mkac05) {
        this.mkac05 = mkac05 == null ? null : mkac05.trim();
    }

    /**
     * 获取：f58k0101-MKDL05
     *
     * @return MKDL05
     */
    public String getMkdl05() {
        return mkdl05;
    }

    /**
     * 设置：f58k0101-MKDL05
     *
     * @param mkdl05 f58k0101-MKDL05
     */
    public void setMkdl05(String mkdl05) {
        this.mkdl05 = mkdl05 == null ? null : mkdl05.trim();
    }

    /**
     * 获取：f58k0101-MKAC06
     *
     * @return MKAC06
     */
    public String getMkac06() {
        return mkac06;
    }

    /**
     * 设置：f58k0101-MKAC06
     *
     * @param mkac06 f58k0101-MKAC06
     */
    public void setMkac06(String mkac06) {
        this.mkac06 = mkac06 == null ? null : mkac06.trim();
    }

    /**
     * 获取：f58k0101-MKDL06
     *
     * @return MKDL06
     */
    public String getMkdl06() {
        return mkdl06;
    }

    /**
     * 设置：f58k0101-MKDL06
     *
     * @param mkdl06 f58k0101-MKDL06
     */
    public void setMkdl06(String mkdl06) {
        this.mkdl06 = mkdl06 == null ? null : mkdl06.trim();
    }

    /**
     * 获取：f58k0101-MKAC07
     *
     * @return MKAC07
     */
    public String getMkac07() {
        return mkac07;
    }

    /**
     * 设置：f58k0101-MKAC07
     *
     * @param mkac07 f58k0101-MKAC07
     */
    public void setMkac07(String mkac07) {
        this.mkac07 = mkac07 == null ? null : mkac07.trim();
    }

    /**
     * 获取：f58k0101-MKDL07
     *
     * @return MKDL07
     */
    public String getMkdl07() {
        return mkdl07;
    }

    /**
     * 设置：f58k0101-MKDL07
     *
     * @param mkdl07 f58k0101-MKDL07
     */
    public void setMkdl07(String mkdl07) {
        this.mkdl07 = mkdl07 == null ? null : mkdl07.trim();
    }

    /**
     * 获取：f58k0101-MKAC08
     *
     * @return MKAC08
     */
    public String getMkac08() {
        return mkac08;
    }

    /**
     * 设置：f58k0101-MKAC08
     *
     * @param mkac08 f58k0101-MKAC08
     */
    public void setMkac08(String mkac08) {
        this.mkac08 = mkac08 == null ? null : mkac08.trim();
    }

    /**
     * 获取：f58k0101-MKDL08
     *
     * @return MKDL08
     */
    public String getMkdl08() {
        return mkdl08;
    }

    /**
     * 设置：f58k0101-MKDL08
     *
     * @param mkdl08 f58k0101-MKDL08
     */
    public void setMkdl08(String mkdl08) {
        this.mkdl08 = mkdl08 == null ? null : mkdl08.trim();
    }

    /**
     * 获取：f58k0101-MKUSER
     *
     * @return MKUSER
     */
    public String getMkuser() {
        return mkuser;
    }

    /**
     * 设置：f58k0101-MKUSER
     *
     * @param mkuser f58k0101-MKUSER
     */
    public void setMkuser(String mkuser) {
        this.mkuser = mkuser == null ? null : mkuser.trim();
    }

    /**
     * 获取：f58k0101-MKPID
     *
     * @return MKPID
     */
    public String getMkpid() {
        return mkpid;
    }

    /**
     * 设置：f58k0101-MKPID
     *
     * @param mkpid f58k0101-MKPID
     */
    public void setMkpid(String mkpid) {
        this.mkpid = mkpid == null ? null : mkpid.trim();
    }

    /**
     * 获取：f58k0101-MKJOBN
     *
     * @return MKJOBN
     */
    public String getMkjobn() {
        return mkjobn;
    }

    /**
     * 设置：f58k0101-MKJOBN
     *
     * @param mkjobn f58k0101-MKJOBN
     */
    public void setMkjobn(String mkjobn) {
        this.mkjobn = mkjobn == null ? null : mkjobn.trim();
    }

    /**
     * 获取：f58k0101-MKUPMJ
     *
     * @return MKUPMJ
     */
    public Date getMkupmj() {
        return mkupmj;
    }

    /**
     * 设置：f58k0101-MKUPMJ
     *
     * @param mkupmj f58k0101-MKUPMJ
     */
    public void setMkupmj(Date mkupmj) {
        this.mkupmj = mkupmj;
    }

    /**
     * 获取：f58k0101-MKUPMT
     *
     * @return MKUPMT
     */
    public String getMkupmt() {
        return mkupmt;
    }

    /**
     * 设置：f58k0101-MKUPMT
     *
     * @param mkupmt f58k0101-MKUPMT
     */
    public void setMkupmt(String mkupmt) {
        this.mkupmt = mkupmt == null ? null : mkupmt.trim();
    }
}