package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * f58k4106
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58K4106DO implements Serializable {
    /**
     * f58k4106-MNLITM
     */
    private String mnlitm;

    /**
     * f58k4106-MNMCU
     */
    private String mnmcu;

    /**
     * f58k4106-MNEFTJ
     */
    private Date mneftj;

    /**
     * f58k4106-MNEXDJ
     */
    private Date mnexdj;

    /**
     * f58k4106-MNUPRC
     */
    private BigDecimal mnuprc;

    /**
     * f58k4106-MNUSER
     */
    private String mnuser;

    /**
     * f58k4106-MNPID
     */
    private String mnpid;

    /**
     * f58k4106-MNJOBN
     */
    private String mnjobn;

    /**
     * f58k4106-MNUPMJ
     */
    private Date mnupmj;

    /**
     * f58k4106-MNTDAY
     */
    private String mntday;

    /**
     * f58k4106-MNFLAG
     */
    private String mnflag;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：f58k4106-MNLITM
     *
     * @return MNLITM
     */
    public String getMnlitm() {
        return mnlitm;
    }

    /**
     * 设置：f58k4106-MNLITM
     *
     * @param mnlitm f58k4106-MNLITM
     */
    public void setMnlitm(String mnlitm) {
        this.mnlitm = mnlitm == null ? null : mnlitm.trim();
    }

    /**
     * 获取：f58k4106-MNMCU
     *
     * @return MNMCU
     */
    public String getMnmcu() {
        return mnmcu;
    }

    /**
     * 设置：f58k4106-MNMCU
     *
     * @param mnmcu f58k4106-MNMCU
     */
    public void setMnmcu(String mnmcu) {
        this.mnmcu = mnmcu == null ? null : mnmcu.trim();
    }

    /**
     * 获取：f58k4106-MNEFTJ
     *
     * @return MNEFTJ
     */
    public Date getMneftj() {
        return mneftj;
    }

    /**
     * 设置：f58k4106-MNEFTJ
     *
     * @param mneftj f58k4106-MNEFTJ
     */
    public void setMneftj(Date mneftj) {
        this.mneftj = mneftj;
    }

    /**
     * 获取：f58k4106-MNEXDJ
     *
     * @return MNEXDJ
     */
    public Date getMnexdj() {
        return mnexdj;
    }

    /**
     * 设置：f58k4106-MNEXDJ
     *
     * @param mnexdj f58k4106-MNEXDJ
     */
    public void setMnexdj(Date mnexdj) {
        this.mnexdj = mnexdj;
    }

    /**
     * 获取：f58k4106-MNUPRC
     *
     * @return MNUPRC
     */
    public BigDecimal getMnuprc() {
        return mnuprc;
    }

    /**
     * 设置：f58k4106-MNUPRC
     *
     * @param mnuprc f58k4106-MNUPRC
     */
    public void setMnuprc(BigDecimal mnuprc) {
        this.mnuprc = mnuprc;
    }

    /**
     * 获取：f58k4106-MNUSER
     *
     * @return MNUSER
     */
    public String getMnuser() {
        return mnuser;
    }

    /**
     * 设置：f58k4106-MNUSER
     *
     * @param mnuser f58k4106-MNUSER
     */
    public void setMnuser(String mnuser) {
        this.mnuser = mnuser == null ? null : mnuser.trim();
    }

    /**
     * 获取：f58k4106-MNPID
     *
     * @return MNPID
     */
    public String getMnpid() {
        return mnpid;
    }

    /**
     * 设置：f58k4106-MNPID
     *
     * @param mnpid f58k4106-MNPID
     */
    public void setMnpid(String mnpid) {
        this.mnpid = mnpid == null ? null : mnpid.trim();
    }

    /**
     * 获取：f58k4106-MNJOBN
     *
     * @return MNJOBN
     */
    public String getMnjobn() {
        return mnjobn;
    }

    /**
     * 设置：f58k4106-MNJOBN
     *
     * @param mnjobn f58k4106-MNJOBN
     */
    public void setMnjobn(String mnjobn) {
        this.mnjobn = mnjobn == null ? null : mnjobn.trim();
    }

    /**
     * 获取：f58k4106-MNUPMJ
     *
     * @return MNUPMJ
     */
    public Date getMnupmj() {
        return mnupmj;
    }

    /**
     * 设置：f58k4106-MNUPMJ
     *
     * @param mnupmj f58k4106-MNUPMJ
     */
    public void setMnupmj(Date mnupmj) {
        this.mnupmj = mnupmj;
    }

    /**
     * 获取：f58k4106-MNTDAY
     *
     * @return MNTDAY
     */
    public String getMntday() {
        return mntday;
    }

    /**
     * 设置：f58k4106-MNTDAY
     *
     * @param mntday f58k4106-MNTDAY
     */
    public void setMntday(String mntday) {
        this.mntday = mntday == null ? null : mntday.trim();
    }

    /**
     * 获取：f58k4106-MNFLAG
     *
     * @return MNFLAG
     */
    public String getMnflag() {
        return mnflag;
    }

    /**
     * 设置：f58k4106-MNFLAG
     *
     * @param mnflag f58k4106-MNFLAG
     */
    public void setMnflag(String mnflag) {
        this.mnflag = mnflag == null ? null : mnflag.trim();
    }
}