package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * f58k4710
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58K4710DO implements Serializable {
    /**
     * f58k4710-CKKCOO
     */
    private String ckkcoo;

    /**
     * f58k4710-CKDOCO
     */
    private Integer ckdoco;

    /**
     * f58k4710-CKDCTO
     */
    private String ckdcto;

    /**
     * f58k4710-CKLNID
     */
    private BigDecimal cklnid;

    /**
     * f58k4710-CKMMCU
     */
    private String ckmmcu;

    /**
     * f58k4710-CKMCU
     */
    private String ckmcu;

    /**
     * f58k4710-CKSHAN
     */
    private Integer ckshan;

    /**
     * f58k4710-CKVR01
     */
    private String ckvr01;

    /**
     * f58k4710-CKRKCO
     */
    private String ckrkco;

    /**
     * f58k4710-CKRORN
     */
    private String ckrorn;

    /**
     * f58k4710-CKRCTO
     */
    private String ckrcto;

    /**
     * f58k4710-CKRLLN
     */
    private BigDecimal ckrlln;

    /**
     * f58k4710-CKLITM
     */
    private String cklitm;

    /**
     * f58k4710-CKUORG
     */
    private BigDecimal ckuorg;

    /**
     * f58k4710-CKUOM1
     */
    private String ckuom1;

    /**
     * f58k4710-CKSOQS
     */
    private BigDecimal cksoqs;

    /**
     * f58k4710-CKUOM6
     */
    private String ckuom6;

    /**
     * f58k4710-CKTRDJ
     */
    private Date cktrdj;

    /**
     * f58k4710-CKADDJ
     */
    private Date ckaddj;

    /**
     * f58k4710-CKE58DDRQ
     */
    private String cke58ddrq;

    /**
     * f58k4710-CKE58FYRQ
     */
    private String cke58fyrq;

    /**
     * f58k4710-CKLOCN
     */
    private String cklocn;

    /**
     * f58k4710-CKLOTN
     */
    private String cklotn;

    /**
     * f58k4710-CKU4DJ
     */
    private Date cku4dj;

    /**
     * f58k4710-CKMMEJ
     */
    private Date ckmmej;

    /**
     * f58k4710-CKURCD
     */
    private String ckurcd;

    /**
     * f58k4710-CKURDT
     */
    private String ckurdt;

    /**
     * f58k4710-CKURAT
     */
    private BigDecimal ckurat;

    /**
     * f58k4710-CKURAB
     */
    private Integer ckurab;

    /**
     * f58k4710-CKURRF
     */
    private String ckurrf;

    /**
     * f58k4710-CKEV01
     */
    private String ckev01;

    /**
     * f58k4710-CKEV02
     */
    private String ckev02;

    /**
     * f58k4710-CKEV03
     */
    private String ckev03;

    /**
     * f58k4710-CKUSER
     */
    private String ckuser;

    /**
     * f58k4710-CKPID
     */
    private String ckpid;

    /**
     * f58k4710-CKJOBN
     */
    private String ckjobn;

    /**
     * f58k4710-CKUPMJ
     */
    private Date ckupmj;

    /**
     * f58k4710-CKUPMT
     */
    private Long ckupmt;

    /**
     * f58k4710-CKUPRC
     */
    private BigDecimal ckuprc;

    /**
     * f58k4710-CKAEXP
     */
    private BigDecimal ckaexp;

    /**
     * f58k4710-CKAN8
     */
    private Integer ckan8;

    /**
     * f58k4710-CKINDATE
     */
    private Date ckindate;

    /**
     * f58k4710-CKINRMK
     */
    private String ckinrmk;

    /**
     * f58k4710-CKREDATE
     */
    private Date ckredate;

    /**
     * f58k4710-CKRERMK
     */
    private String ckrermk;

    /**
     * f58k4710-CKUKID
     */
    private Integer ckukid;

    /**
     * f58k4710-CKSTATUS
     */
    private String ckstatus;

    /**
     * f58k4710-CKFLAG
     */
    private String ckflag;

    /**
     * f58k4710-CKTXR1
     */
    private Long cktxr1;

    /**
     * f58k4710-CKTUPRC
     */
    private Long cktuprc;

    /**
     * f58k4710-CKTAEXP
     */
    private Long cktaexp;

    /**
     * f58k4710-CKETA
     */
    private Long cketa;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：f58k4710-CKKCOO
     *
     * @return CKKCOO
     */
    public String getCkkcoo() {
        return ckkcoo;
    }

    /**
     * 设置：f58k4710-CKKCOO
     *
     * @param ckkcoo f58k4710-CKKCOO
     */
    public void setCkkcoo(String ckkcoo) {
        this.ckkcoo = ckkcoo == null ? null : ckkcoo.trim();
    }

    /**
     * 获取：f58k4710-CKDOCO
     *
     * @return CKDOCO
     */
    public Integer getCkdoco() {
        return ckdoco;
    }

    /**
     * 设置：f58k4710-CKDOCO
     *
     * @param ckdoco f58k4710-CKDOCO
     */
    public void setCkdoco(Integer ckdoco) {
        this.ckdoco = ckdoco;
    }

    /**
     * 获取：f58k4710-CKDCTO
     *
     * @return CKDCTO
     */
    public String getCkdcto() {
        return ckdcto;
    }

    /**
     * 设置：f58k4710-CKDCTO
     *
     * @param ckdcto f58k4710-CKDCTO
     */
    public void setCkdcto(String ckdcto) {
        this.ckdcto = ckdcto == null ? null : ckdcto.trim();
    }

    /**
     * 获取：f58k4710-CKLNID
     *
     * @return CKLNID
     */
    public BigDecimal getCklnid() {
        return cklnid;
    }

    /**
     * 设置：f58k4710-CKLNID
     *
     * @param cklnid f58k4710-CKLNID
     */
    public void setCklnid(BigDecimal cklnid) {
        this.cklnid = cklnid;
    }

    /**
     * 获取：f58k4710-CKMMCU
     *
     * @return CKMMCU
     */
    public String getCkmmcu() {
        return ckmmcu;
    }

    /**
     * 设置：f58k4710-CKMMCU
     *
     * @param ckmmcu f58k4710-CKMMCU
     */
    public void setCkmmcu(String ckmmcu) {
        this.ckmmcu = ckmmcu == null ? null : ckmmcu.trim();
    }

    /**
     * 获取：f58k4710-CKMCU
     *
     * @return CKMCU
     */
    public String getCkmcu() {
        return ckmcu;
    }

    /**
     * 设置：f58k4710-CKMCU
     *
     * @param ckmcu f58k4710-CKMCU
     */
    public void setCkmcu(String ckmcu) {
        this.ckmcu = ckmcu == null ? null : ckmcu.trim();
    }

    /**
     * 获取：f58k4710-CKSHAN
     *
     * @return CKSHAN
     */
    public Integer getCkshan() {
        return ckshan;
    }

    /**
     * 设置：f58k4710-CKSHAN
     *
     * @param ckshan f58k4710-CKSHAN
     */
    public void setCkshan(Integer ckshan) {
        this.ckshan = ckshan;
    }

    /**
     * 获取：f58k4710-CKVR01
     *
     * @return CKVR01
     */
    public String getCkvr01() {
        return ckvr01;
    }

    /**
     * 设置：f58k4710-CKVR01
     *
     * @param ckvr01 f58k4710-CKVR01
     */
    public void setCkvr01(String ckvr01) {
        this.ckvr01 = ckvr01 == null ? null : ckvr01.trim();
    }

    /**
     * 获取：f58k4710-CKRKCO
     *
     * @return CKRKCO
     */
    public String getCkrkco() {
        return ckrkco;
    }

    /**
     * 设置：f58k4710-CKRKCO
     *
     * @param ckrkco f58k4710-CKRKCO
     */
    public void setCkrkco(String ckrkco) {
        this.ckrkco = ckrkco == null ? null : ckrkco.trim();
    }

    /**
     * 获取：f58k4710-CKRORN
     *
     * @return CKRORN
     */
    public String getCkrorn() {
        return ckrorn;
    }

    /**
     * 设置：f58k4710-CKRORN
     *
     * @param ckrorn f58k4710-CKRORN
     */
    public void setCkrorn(String ckrorn) {
        this.ckrorn = ckrorn == null ? null : ckrorn.trim();
    }

    /**
     * 获取：f58k4710-CKRCTO
     *
     * @return CKRCTO
     */
    public String getCkrcto() {
        return ckrcto;
    }

    /**
     * 设置：f58k4710-CKRCTO
     *
     * @param ckrcto f58k4710-CKRCTO
     */
    public void setCkrcto(String ckrcto) {
        this.ckrcto = ckrcto == null ? null : ckrcto.trim();
    }

    /**
     * 获取：f58k4710-CKRLLN
     *
     * @return CKRLLN
     */
    public BigDecimal getCkrlln() {
        return ckrlln;
    }

    /**
     * 设置：f58k4710-CKRLLN
     *
     * @param ckrlln f58k4710-CKRLLN
     */
    public void setCkrlln(BigDecimal ckrlln) {
        this.ckrlln = ckrlln;
    }

    /**
     * 获取：f58k4710-CKLITM
     *
     * @return CKLITM
     */
    public String getCklitm() {
        return cklitm;
    }

    /**
     * 设置：f58k4710-CKLITM
     *
     * @param cklitm f58k4710-CKLITM
     */
    public void setCklitm(String cklitm) {
        this.cklitm = cklitm == null ? null : cklitm.trim();
    }

    /**
     * 获取：f58k4710-CKUORG
     *
     * @return CKUORG
     */
    public BigDecimal getCkuorg() {
        return ckuorg;
    }

    /**
     * 设置：f58k4710-CKUORG
     *
     * @param ckuorg f58k4710-CKUORG
     */
    public void setCkuorg(BigDecimal ckuorg) {
        this.ckuorg = ckuorg;
    }

    /**
     * 获取：f58k4710-CKUOM1
     *
     * @return CKUOM1
     */
    public String getCkuom1() {
        return ckuom1;
    }

    /**
     * 设置：f58k4710-CKUOM1
     *
     * @param ckuom1 f58k4710-CKUOM1
     */
    public void setCkuom1(String ckuom1) {
        this.ckuom1 = ckuom1 == null ? null : ckuom1.trim();
    }

    /**
     * 获取：f58k4710-CKSOQS
     *
     * @return CKSOQS
     */
    public BigDecimal getCksoqs() {
        return cksoqs;
    }

    /**
     * 设置：f58k4710-CKSOQS
     *
     * @param cksoqs f58k4710-CKSOQS
     */
    public void setCksoqs(BigDecimal cksoqs) {
        this.cksoqs = cksoqs;
    }

    /**
     * 获取：f58k4710-CKUOM6
     *
     * @return CKUOM6
     */
    public String getCkuom6() {
        return ckuom6;
    }

    /**
     * 设置：f58k4710-CKUOM6
     *
     * @param ckuom6 f58k4710-CKUOM6
     */
    public void setCkuom6(String ckuom6) {
        this.ckuom6 = ckuom6 == null ? null : ckuom6.trim();
    }

    /**
     * 获取：f58k4710-CKTRDJ
     *
     * @return CKTRDJ
     */
    public Date getCktrdj() {
        return cktrdj;
    }

    /**
     * 设置：f58k4710-CKTRDJ
     *
     * @param cktrdj f58k4710-CKTRDJ
     */
    public void setCktrdj(Date cktrdj) {
        this.cktrdj = cktrdj;
    }

    /**
     * 获取：f58k4710-CKADDJ
     *
     * @return CKADDJ
     */
    public Date getCkaddj() {
        return ckaddj;
    }

    /**
     * 设置：f58k4710-CKADDJ
     *
     * @param ckaddj f58k4710-CKADDJ
     */
    public void setCkaddj(Date ckaddj) {
        this.ckaddj = ckaddj;
    }

    /**
     * 获取：f58k4710-CKE58DDRQ
     *
     * @return CKE58DDRQ
     */
    public String getCke58ddrq() {
        return cke58ddrq;
    }

    /**
     * 设置：f58k4710-CKE58DDRQ
     *
     * @param cke58ddrq f58k4710-CKE58DDRQ
     */
    public void setCke58ddrq(String cke58ddrq) {
        this.cke58ddrq = cke58ddrq == null ? null : cke58ddrq.trim();
    }

    /**
     * 获取：f58k4710-CKE58FYRQ
     *
     * @return CKE58FYRQ
     */
    public String getCke58fyrq() {
        return cke58fyrq;
    }

    /**
     * 设置：f58k4710-CKE58FYRQ
     *
     * @param cke58fyrq f58k4710-CKE58FYRQ
     */
    public void setCke58fyrq(String cke58fyrq) {
        this.cke58fyrq = cke58fyrq == null ? null : cke58fyrq.trim();
    }

    /**
     * 获取：f58k4710-CKLOCN
     *
     * @return CKLOCN
     */
    public String getCklocn() {
        return cklocn;
    }

    /**
     * 设置：f58k4710-CKLOCN
     *
     * @param cklocn f58k4710-CKLOCN
     */
    public void setCklocn(String cklocn) {
        this.cklocn = cklocn == null ? null : cklocn.trim();
    }

    /**
     * 获取：f58k4710-CKLOTN
     *
     * @return CKLOTN
     */
    public String getCklotn() {
        return cklotn;
    }

    /**
     * 设置：f58k4710-CKLOTN
     *
     * @param cklotn f58k4710-CKLOTN
     */
    public void setCklotn(String cklotn) {
        this.cklotn = cklotn == null ? null : cklotn.trim();
    }

    /**
     * 获取：f58k4710-CKU4DJ
     *
     * @return CKU4DJ
     */
    public Date getCku4dj() {
        return cku4dj;
    }

    /**
     * 设置：f58k4710-CKU4DJ
     *
     * @param cku4dj f58k4710-CKU4DJ
     */
    public void setCku4dj(Date cku4dj) {
        this.cku4dj = cku4dj;
    }

    /**
     * 获取：f58k4710-CKMMEJ
     *
     * @return CKMMEJ
     */
    public Date getCkmmej() {
        return ckmmej;
    }

    /**
     * 设置：f58k4710-CKMMEJ
     *
     * @param ckmmej f58k4710-CKMMEJ
     */
    public void setCkmmej(Date ckmmej) {
        this.ckmmej = ckmmej;
    }

    /**
     * 获取：f58k4710-CKURCD
     *
     * @return CKURCD
     */
    public String getCkurcd() {
        return ckurcd;
    }

    /**
     * 设置：f58k4710-CKURCD
     *
     * @param ckurcd f58k4710-CKURCD
     */
    public void setCkurcd(String ckurcd) {
        this.ckurcd = ckurcd == null ? null : ckurcd.trim();
    }

    /**
     * 获取：f58k4710-CKURDT
     *
     * @return CKURDT
     */
    public String getCkurdt() {
        return ckurdt;
    }

    /**
     * 设置：f58k4710-CKURDT
     *
     * @param ckurdt f58k4710-CKURDT
     */
    public void setCkurdt(String ckurdt) {
        this.ckurdt = ckurdt == null ? null : ckurdt.trim();
    }

    /**
     * 获取：f58k4710-CKURAT
     *
     * @return CKURAT
     */
    public BigDecimal getCkurat() {
        return ckurat;
    }

    /**
     * 设置：f58k4710-CKURAT
     *
     * @param ckurat f58k4710-CKURAT
     */
    public void setCkurat(BigDecimal ckurat) {
        this.ckurat = ckurat;
    }

    /**
     * 获取：f58k4710-CKURAB
     *
     * @return CKURAB
     */
    public Integer getCkurab() {
        return ckurab;
    }

    /**
     * 设置：f58k4710-CKURAB
     *
     * @param ckurab f58k4710-CKURAB
     */
    public void setCkurab(Integer ckurab) {
        this.ckurab = ckurab;
    }

    /**
     * 获取：f58k4710-CKURRF
     *
     * @return CKURRF
     */
    public String getCkurrf() {
        return ckurrf;
    }

    /**
     * 设置：f58k4710-CKURRF
     *
     * @param ckurrf f58k4710-CKURRF
     */
    public void setCkurrf(String ckurrf) {
        this.ckurrf = ckurrf == null ? null : ckurrf.trim();
    }

    /**
     * 获取：f58k4710-CKEV01
     *
     * @return CKEV01
     */
    public String getCkev01() {
        return ckev01;
    }

    /**
     * 设置：f58k4710-CKEV01
     *
     * @param ckev01 f58k4710-CKEV01
     */
    public void setCkev01(String ckev01) {
        this.ckev01 = ckev01 == null ? null : ckev01.trim();
    }

    /**
     * 获取：f58k4710-CKEV02
     *
     * @return CKEV02
     */
    public String getCkev02() {
        return ckev02;
    }

    /**
     * 设置：f58k4710-CKEV02
     *
     * @param ckev02 f58k4710-CKEV02
     */
    public void setCkev02(String ckev02) {
        this.ckev02 = ckev02 == null ? null : ckev02.trim();
    }

    /**
     * 获取：f58k4710-CKEV03
     *
     * @return CKEV03
     */
    public String getCkev03() {
        return ckev03;
    }

    /**
     * 设置：f58k4710-CKEV03
     *
     * @param ckev03 f58k4710-CKEV03
     */
    public void setCkev03(String ckev03) {
        this.ckev03 = ckev03 == null ? null : ckev03.trim();
    }

    /**
     * 获取：f58k4710-CKUSER
     *
     * @return CKUSER
     */
    public String getCkuser() {
        return ckuser;
    }

    /**
     * 设置：f58k4710-CKUSER
     *
     * @param ckuser f58k4710-CKUSER
     */
    public void setCkuser(String ckuser) {
        this.ckuser = ckuser == null ? null : ckuser.trim();
    }

    /**
     * 获取：f58k4710-CKPID
     *
     * @return CKPID
     */
    public String getCkpid() {
        return ckpid;
    }

    /**
     * 设置：f58k4710-CKPID
     *
     * @param ckpid f58k4710-CKPID
     */
    public void setCkpid(String ckpid) {
        this.ckpid = ckpid == null ? null : ckpid.trim();
    }

    /**
     * 获取：f58k4710-CKJOBN
     *
     * @return CKJOBN
     */
    public String getCkjobn() {
        return ckjobn;
    }

    /**
     * 设置：f58k4710-CKJOBN
     *
     * @param ckjobn f58k4710-CKJOBN
     */
    public void setCkjobn(String ckjobn) {
        this.ckjobn = ckjobn == null ? null : ckjobn.trim();
    }

    /**
     * 获取：f58k4710-CKUPMJ
     *
     * @return CKUPMJ
     */
    public Date getCkupmj() {
        return ckupmj;
    }

    /**
     * 设置：f58k4710-CKUPMJ
     *
     * @param ckupmj f58k4710-CKUPMJ
     */
    public void setCkupmj(Date ckupmj) {
        this.ckupmj = ckupmj;
    }

    /**
     * 获取：f58k4710-CKUPMT
     *
     * @return CKUPMT
     */
    public Long getCkupmt() {
        return ckupmt;
    }

    /**
     * 设置：f58k4710-CKUPMT
     *
     * @param ckupmt f58k4710-CKUPMT
     */
    public void setCkupmt(Long ckupmt) {
        this.ckupmt = ckupmt;
    }

    /**
     * 获取：f58k4710-CKUPRC
     *
     * @return CKUPRC
     */
    public BigDecimal getCkuprc() {
        return ckuprc;
    }

    /**
     * 设置：f58k4710-CKUPRC
     *
     * @param ckuprc f58k4710-CKUPRC
     */
    public void setCkuprc(BigDecimal ckuprc) {
        this.ckuprc = ckuprc;
    }

    /**
     * 获取：f58k4710-CKAEXP
     *
     * @return CKAEXP
     */
    public BigDecimal getCkaexp() {
        return ckaexp;
    }

    /**
     * 设置：f58k4710-CKAEXP
     *
     * @param ckaexp f58k4710-CKAEXP
     */
    public void setCkaexp(BigDecimal ckaexp) {
        this.ckaexp = ckaexp;
    }

    /**
     * 获取：f58k4710-CKAN8
     *
     * @return CKAN8
     */
    public Integer getCkan8() {
        return ckan8;
    }

    /**
     * 设置：f58k4710-CKAN8
     *
     * @param ckan8 f58k4710-CKAN8
     */
    public void setCkan8(Integer ckan8) {
        this.ckan8 = ckan8;
    }

    /**
     * 获取：f58k4710-CKINDATE
     *
     * @return CKINDATE
     */
    public Date getCkindate() {
        return ckindate;
    }

    /**
     * 设置：f58k4710-CKINDATE
     *
     * @param ckindate f58k4710-CKINDATE
     */
    public void setCkindate(Date ckindate) {
        this.ckindate = ckindate;
    }

    /**
     * 获取：f58k4710-CKINRMK
     *
     * @return CKINRMK
     */
    public String getCkinrmk() {
        return ckinrmk;
    }

    /**
     * 设置：f58k4710-CKINRMK
     *
     * @param ckinrmk f58k4710-CKINRMK
     */
    public void setCkinrmk(String ckinrmk) {
        this.ckinrmk = ckinrmk == null ? null : ckinrmk.trim();
    }

    /**
     * 获取：f58k4710-CKREDATE
     *
     * @return CKREDATE
     */
    public Date getCkredate() {
        return ckredate;
    }

    /**
     * 设置：f58k4710-CKREDATE
     *
     * @param ckredate f58k4710-CKREDATE
     */
    public void setCkredate(Date ckredate) {
        this.ckredate = ckredate;
    }

    /**
     * 获取：f58k4710-CKRERMK
     *
     * @return CKRERMK
     */
    public String getCkrermk() {
        return ckrermk;
    }

    /**
     * 设置：f58k4710-CKRERMK
     *
     * @param ckrermk f58k4710-CKRERMK
     */
    public void setCkrermk(String ckrermk) {
        this.ckrermk = ckrermk == null ? null : ckrermk.trim();
    }

    /**
     * 获取：f58k4710-CKUKID
     *
     * @return CKUKID
     */
    public Integer getCkukid() {
        return ckukid;
    }

    /**
     * 设置：f58k4710-CKUKID
     *
     * @param ckukid f58k4710-CKUKID
     */
    public void setCkukid(Integer ckukid) {
        this.ckukid = ckukid;
    }

    /**
     * 获取：f58k4710-CKSTATUS
     *
     * @return CKSTATUS
     */
    public String getCkstatus() {
        return ckstatus;
    }

    /**
     * 设置：f58k4710-CKSTATUS
     *
     * @param ckstatus f58k4710-CKSTATUS
     */
    public void setCkstatus(String ckstatus) {
        this.ckstatus = ckstatus == null ? null : ckstatus.trim();
    }

    /**
     * 获取：f58k4710-CKFLAG
     *
     * @return CKFLAG
     */
    public String getCkflag() {
        return ckflag;
    }

    /**
     * 设置：f58k4710-CKFLAG
     *
     * @param ckflag f58k4710-CKFLAG
     */
    public void setCkflag(String ckflag) {
        this.ckflag = ckflag == null ? null : ckflag.trim();
    }

    /**
     * 获取：f58k4710-CKTXR1
     *
     * @return CKTXR1
     */
    public Long getCktxr1() {
        return cktxr1;
    }

    /**
     * 设置：f58k4710-CKTXR1
     *
     * @param cktxr1 f58k4710-CKTXR1
     */
    public void setCktxr1(Long cktxr1) {
        this.cktxr1 = cktxr1;
    }

    /**
     * 获取：f58k4710-CKTUPRC
     *
     * @return CKTUPRC
     */
    public Long getCktuprc() {
        return cktuprc;
    }

    /**
     * 设置：f58k4710-CKTUPRC
     *
     * @param cktuprc f58k4710-CKTUPRC
     */
    public void setCktuprc(Long cktuprc) {
        this.cktuprc = cktuprc;
    }

    /**
     * 获取：f58k4710-CKTAEXP
     *
     * @return CKTAEXP
     */
    public Long getCktaexp() {
        return cktaexp;
    }

    /**
     * 设置：f58k4710-CKTAEXP
     *
     * @param cktaexp f58k4710-CKTAEXP
     */
    public void setCktaexp(Long cktaexp) {
        this.cktaexp = cktaexp;
    }

    /**
     * 获取：f58k4710-CKETA
     *
     * @return CKETA
     */
    public Long getCketa() {
        return cketa;
    }

    /**
     * 设置：f58k4710-CKETA
     *
     * @param cketa f58k4710-CKETA
     */
    public void setCketa(Long cketa) {
        this.cketa = cketa;
    }
}