package com.ztesoft.zsmart.nros.sbc.nrosuser.plugin.jde.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 * f58k0921
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-05-06
 */
public class F58K0921DO implements Serializable {
    /**
     * f58k0921-M1EDOC
     */
    private Integer m1edoc;

    /**
     * f58k0921-M1EDCT
     */
    private String m1edct;

    /**
     * f58k0921-M1EKCO
     */
    private String m1ekco;

    /**
     * f58k0921-M1EDTY
     */
    private String m1edty;

    /**
     * f58k0921-M1EDSQ
     */
    private Integer m1edsq;

    /**
     * f58k0921-M1EDLN
     */
    private Integer m1edln;

    /**
     * f58k0921-M1EDST
     */
    private String m1edst;

    /**
     * f58k0921-M1EDFT
     */
    private String m1edft;

    /**
     * f58k0921-M1EDDT
     */
    private Date m1eddt;

    /**
     * f58k0921-M1EDER
     */
    private String m1eder;

    /**
     * f58k0921-M1EDDL
     */
    private Integer m1eddl;

    /**
     * f58k0921-M1EDSP
     */
    private String m1edsp;

    /**
     * f58k0921-M1EDBT
     */
    private String m1edbt;

    /**
     * f58k0921-M1PNID
     */
    private String m1pnid;

    /**
     * f58k0921-M1THCD
     */
    private String m1thcd;

    /**
     * f58k0921-M1AN8
     */
    private Integer m1an8;

    /**
     * f58k0921-M1DTFR
     */
    private Integer m1dtfr;

    /**
     * f58k0921-M1DTTO
     */
    private Integer m1dtto;

    /**
     * f58k0921-M1VR01
     */
    private String m1vr01;

    /**
     * f58k0921-M1URCD
     */
    private String m1urcd;

    /**
     * f58k0921-M1URDT
     */
    private Integer m1urdt;

    /**
     * f58k0921-M1URAT
     */
    private Integer m1urat;

    /**
     * f58k0921-M1URAB
     */
    private Integer m1urab;

    /**
     * f58k0921-M1URRF
     */
    private String m1urrf;

    /**
     * f58k0921-M1TORG
     */
    private String m1torg;

    /**
     * f58k0921-M1USER
     */
    private String m1user;

    /**
     * f58k0921-M1PID
     */
    private String m1pid;

    /**
     * f58k0921-M1JOBN
     */
    private String m1jobn;

    /**
     * f58k0921-M1UPMJ
     */
    private Date m1upmj;

    /**
     * f58k0921-M1TDAY
     */
    private String m1tday;

    /**
     * f58k0921-M1GAN8
     */
    private Integer m1gan8;

    /**
     * f58k0921-M1FLAG
     */
    private String m1flag;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：f58k0921-M1EDOC
     *
     * @return M1EDOC
     */
    public Integer getM1edoc() {
        return m1edoc;
    }

    /**
     * 设置：f58k0921-M1EDOC
     *
     * @param m1edoc f58k0921-M1EDOC
     */
    public void setM1edoc(Integer m1edoc) {
        this.m1edoc = m1edoc;
    }

    /**
     * 获取：f58k0921-M1EDCT
     *
     * @return M1EDCT
     */
    public String getM1edct() {
        return m1edct;
    }

    /**
     * 设置：f58k0921-M1EDCT
     *
     * @param m1edct f58k0921-M1EDCT
     */
    public void setM1edct(String m1edct) {
        this.m1edct = m1edct == null ? null : m1edct.trim();
    }

    /**
     * 获取：f58k0921-M1EKCO
     *
     * @return M1EKCO
     */
    public String getM1ekco() {
        return m1ekco;
    }

    /**
     * 设置：f58k0921-M1EKCO
     *
     * @param m1ekco f58k0921-M1EKCO
     */
    public void setM1ekco(String m1ekco) {
        this.m1ekco = m1ekco == null ? null : m1ekco.trim();
    }

    /**
     * 获取：f58k0921-M1EDTY
     *
     * @return M1EDTY
     */
    public String getM1edty() {
        return m1edty;
    }

    /**
     * 设置：f58k0921-M1EDTY
     *
     * @param m1edty f58k0921-M1EDTY
     */
    public void setM1edty(String m1edty) {
        this.m1edty = m1edty == null ? null : m1edty.trim();
    }

    /**
     * 获取：f58k0921-M1EDSQ
     *
     * @return M1EDSQ
     */
    public Integer getM1edsq() {
        return m1edsq;
    }

    /**
     * 设置：f58k0921-M1EDSQ
     *
     * @param m1edsq f58k0921-M1EDSQ
     */
    public void setM1edsq(Integer m1edsq) {
        this.m1edsq = m1edsq;
    }

    /**
     * 获取：f58k0921-M1EDLN
     *
     * @return M1EDLN
     */
    public Integer getM1edln() {
        return m1edln;
    }

    /**
     * 设置：f58k0921-M1EDLN
     *
     * @param m1edln f58k0921-M1EDLN
     */
    public void setM1edln(Integer m1edln) {
        this.m1edln = m1edln;
    }

    /**
     * 获取：f58k0921-M1EDST
     *
     * @return M1EDST
     */
    public String getM1edst() {
        return m1edst;
    }

    /**
     * 设置：f58k0921-M1EDST
     *
     * @param m1edst f58k0921-M1EDST
     */
    public void setM1edst(String m1edst) {
        this.m1edst = m1edst == null ? null : m1edst.trim();
    }

    /**
     * 获取：f58k0921-M1EDFT
     *
     * @return M1EDFT
     */
    public String getM1edft() {
        return m1edft;
    }

    /**
     * 设置：f58k0921-M1EDFT
     *
     * @param m1edft f58k0921-M1EDFT
     */
    public void setM1edft(String m1edft) {
        this.m1edft = m1edft == null ? null : m1edft.trim();
    }

    /**
     * 获取：f58k0921-M1EDDT
     *
     * @return M1EDDT
     */
    public Date getM1eddt() {
        return m1eddt;
    }

    /**
     * 设置：f58k0921-M1EDDT
     *
     * @param m1eddt f58k0921-M1EDDT
     */
    public void setM1eddt(Date m1eddt) {
        this.m1eddt = m1eddt;
    }

    /**
     * 获取：f58k0921-M1EDER
     *
     * @return M1EDER
     */
    public String getM1eder() {
        return m1eder;
    }

    /**
     * 设置：f58k0921-M1EDER
     *
     * @param m1eder f58k0921-M1EDER
     */
    public void setM1eder(String m1eder) {
        this.m1eder = m1eder == null ? null : m1eder.trim();
    }

    /**
     * 获取：f58k0921-M1EDDL
     *
     * @return M1EDDL
     */
    public Integer getM1eddl() {
        return m1eddl;
    }

    /**
     * 设置：f58k0921-M1EDDL
     *
     * @param m1eddl f58k0921-M1EDDL
     */
    public void setM1eddl(Integer m1eddl) {
        this.m1eddl = m1eddl;
    }

    /**
     * 获取：f58k0921-M1EDSP
     *
     * @return M1EDSP
     */
    public String getM1edsp() {
        return m1edsp;
    }

    /**
     * 设置：f58k0921-M1EDSP
     *
     * @param m1edsp f58k0921-M1EDSP
     */
    public void setM1edsp(String m1edsp) {
        this.m1edsp = m1edsp == null ? null : m1edsp.trim();
    }

    /**
     * 获取：f58k0921-M1EDBT
     *
     * @return M1EDBT
     */
    public String getM1edbt() {
        return m1edbt;
    }

    /**
     * 设置：f58k0921-M1EDBT
     *
     * @param m1edbt f58k0921-M1EDBT
     */
    public void setM1edbt(String m1edbt) {
        this.m1edbt = m1edbt == null ? null : m1edbt.trim();
    }

    /**
     * 获取：f58k0921-M1PNID
     *
     * @return M1PNID
     */
    public String getM1pnid() {
        return m1pnid;
    }

    /**
     * 设置：f58k0921-M1PNID
     *
     * @param m1pnid f58k0921-M1PNID
     */
    public void setM1pnid(String m1pnid) {
        this.m1pnid = m1pnid == null ? null : m1pnid.trim();
    }

    /**
     * 获取：f58k0921-M1THCD
     *
     * @return M1THCD
     */
    public String getM1thcd() {
        return m1thcd;
    }

    /**
     * 设置：f58k0921-M1THCD
     *
     * @param m1thcd f58k0921-M1THCD
     */
    public void setM1thcd(String m1thcd) {
        this.m1thcd = m1thcd == null ? null : m1thcd.trim();
    }

    /**
     * 获取：f58k0921-M1AN8
     *
     * @return M1AN8
     */
    public Integer getM1an8() {
        return m1an8;
    }

    /**
     * 设置：f58k0921-M1AN8
     *
     * @param m1an8 f58k0921-M1AN8
     */
    public void setM1an8(Integer m1an8) {
        this.m1an8 = m1an8;
    }

    /**
     * 获取：f58k0921-M1DTFR
     *
     * @return M1DTFR
     */
    public Integer getM1dtfr() {
        return m1dtfr;
    }

    /**
     * 设置：f58k0921-M1DTFR
     *
     * @param m1dtfr f58k0921-M1DTFR
     */
    public void setM1dtfr(Integer m1dtfr) {
        this.m1dtfr = m1dtfr;
    }

    /**
     * 获取：f58k0921-M1DTTO
     *
     * @return M1DTTO
     */
    public Integer getM1dtto() {
        return m1dtto;
    }

    /**
     * 设置：f58k0921-M1DTTO
     *
     * @param m1dtto f58k0921-M1DTTO
     */
    public void setM1dtto(Integer m1dtto) {
        this.m1dtto = m1dtto;
    }

    /**
     * 获取：f58k0921-M1VR01
     *
     * @return M1VR01
     */
    public String getM1vr01() {
        return m1vr01;
    }

    /**
     * 设置：f58k0921-M1VR01
     *
     * @param m1vr01 f58k0921-M1VR01
     */
    public void setM1vr01(String m1vr01) {
        this.m1vr01 = m1vr01 == null ? null : m1vr01.trim();
    }

    /**
     * 获取：f58k0921-M1URCD
     *
     * @return M1URCD
     */
    public String getM1urcd() {
        return m1urcd;
    }

    /**
     * 设置：f58k0921-M1URCD
     *
     * @param m1urcd f58k0921-M1URCD
     */
    public void setM1urcd(String m1urcd) {
        this.m1urcd = m1urcd == null ? null : m1urcd.trim();
    }

    /**
     * 获取：f58k0921-M1URDT
     *
     * @return M1URDT
     */
    public Integer getM1urdt() {
        return m1urdt;
    }

    /**
     * 设置：f58k0921-M1URDT
     *
     * @param m1urdt f58k0921-M1URDT
     */
    public void setM1urdt(Integer m1urdt) {
        this.m1urdt = m1urdt;
    }

    /**
     * 获取：f58k0921-M1URAT
     *
     * @return M1URAT
     */
    public Integer getM1urat() {
        return m1urat;
    }

    /**
     * 设置：f58k0921-M1URAT
     *
     * @param m1urat f58k0921-M1URAT
     */
    public void setM1urat(Integer m1urat) {
        this.m1urat = m1urat;
    }

    /**
     * 获取：f58k0921-M1URAB
     *
     * @return M1URAB
     */
    public Integer getM1urab() {
        return m1urab;
    }

    /**
     * 设置：f58k0921-M1URAB
     *
     * @param m1urab f58k0921-M1URAB
     */
    public void setM1urab(Integer m1urab) {
        this.m1urab = m1urab;
    }

    /**
     * 获取：f58k0921-M1URRF
     *
     * @return M1URRF
     */
    public String getM1urrf() {
        return m1urrf;
    }

    /**
     * 设置：f58k0921-M1URRF
     *
     * @param m1urrf f58k0921-M1URRF
     */
    public void setM1urrf(String m1urrf) {
        this.m1urrf = m1urrf == null ? null : m1urrf.trim();
    }

    /**
     * 获取：f58k0921-M1TORG
     *
     * @return M1TORG
     */
    public String getM1torg() {
        return m1torg;
    }

    /**
     * 设置：f58k0921-M1TORG
     *
     * @param m1torg f58k0921-M1TORG
     */
    public void setM1torg(String m1torg) {
        this.m1torg = m1torg == null ? null : m1torg.trim();
    }

    /**
     * 获取：f58k0921-M1USER
     *
     * @return M1USER
     */
    public String getM1user() {
        return m1user;
    }

    /**
     * 设置：f58k0921-M1USER
     *
     * @param m1user f58k0921-M1USER
     */
    public void setM1user(String m1user) {
        this.m1user = m1user == null ? null : m1user.trim();
    }

    /**
     * 获取：f58k0921-M1PID
     *
     * @return M1PID
     */
    public String getM1pid() {
        return m1pid;
    }

    /**
     * 设置：f58k0921-M1PID
     *
     * @param m1pid f58k0921-M1PID
     */
    public void setM1pid(String m1pid) {
        this.m1pid = m1pid == null ? null : m1pid.trim();
    }

    /**
     * 获取：f58k0921-M1JOBN
     *
     * @return M1JOBN
     */
    public String getM1jobn() {
        return m1jobn;
    }

    /**
     * 设置：f58k0921-M1JOBN
     *
     * @param m1jobn f58k0921-M1JOBN
     */
    public void setM1jobn(String m1jobn) {
        this.m1jobn = m1jobn == null ? null : m1jobn.trim();
    }

    /**
     * 获取：f58k0921-M1UPMJ
     *
     * @return M1UPMJ
     */
    public Date getM1upmj() {
        return m1upmj;
    }

    /**
     * 设置：f58k0921-M1UPMJ
     *
     * @param m1upmj f58k0921-M1UPMJ
     */
    public void setM1upmj(Date m1upmj) {
        this.m1upmj = m1upmj;
    }

    /**
     * 获取：f58k0921-M1TDAY
     *
     * @return M1TDAY
     */
    public String getM1tday() {
        return m1tday;
    }

    /**
     * 设置：f58k0921-M1TDAY
     *
     * @param m1tday f58k0921-M1TDAY
     */
    public void setM1tday(String m1tday) {
        this.m1tday = m1tday == null ? null : m1tday.trim();
    }

    /**
     * 获取：f58k0921-M1GAN8
     *
     * @return M1GAN8
     */
    public Integer getM1gan8() {
        return m1gan8;
    }

    /**
     * 设置：f58k0921-M1GAN8
     *
     * @param m1gan8 f58k0921-M1GAN8
     */
    public void setM1gan8(Integer m1gan8) {
        this.m1gan8 = m1gan8;
    }

    /**
     * 获取：f58k0921-M1FLAG
     *
     * @return M1FLAG
     */
    public String getM1flag() {
        return m1flag;
    }

    /**
     * 设置：f58k0921-M1FLAG
     *
     * @param m1flag f58k0921-M1FLAG
     */
    public void setM1flag(String m1flag) {
        this.m1flag = m1flag == null ? null : m1flag.trim();
    }
}