package com.ztesoft.zsmart.nros.sbc.user.server.dao.dataobject.generator;

import java.io.Serializable;
import java.util.Date;

/**
 * 渠道
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-04-25
 */
public class ChannelDO implements Serializable {
    /**
     * 渠道-id
     */
    private Long id;

    /**
     * 渠道-org_id
     */
    private Long orgId;

    /**
     * 渠道-number
     */
    private String number;

    /**
     * 渠道-name
     */
    private String name;

    /**
     * 渠道-type
     */
    private String type;

    /**
     * 渠道-plat
     */
    private String plat;

    /**
     * 渠道-send_store_id
     */
    private String sendStoreId;

    /**
     * 渠道-refund_store_id
     */
    private String refundStoreId;

    /**
     * 渠道-link_man
     */
    private String linkMan;

    /**
     * 渠道-mobile
     */
    private String mobile;

    /**
     * 渠道-merchant_code
     */
    private String merchantCode;

    /**
     * 渠道-gmt_create
     */
    private Date gmtCreate;

    /**
     * 渠道-gmt_modified
     */
    private Date gmtModified;

    /**
     * 渠道-creator
     */
    private String creator;

    /**
     * 渠道-modifier
     */
    private String modifier;

    /**
     * 渠道-state
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：渠道-id
     *
     * @return id
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：渠道-id
     *
     * @param id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：渠道-org_id
     *
     * @return org_id
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置：渠道-org_id
     *
     * @param orgId
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取：渠道-number
     *
     * @return number
     */
    public String getNumber() {
        return number;
    }

    /**
     * 设置：渠道-number
     *
     * @param number
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * 获取：渠道-name
     *
     * @return name
     */
    public String getName() {
        return name;
    }

    /**
     * 设置：渠道-name
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取：渠道-type
     *
     * @return type
     */
    public String getType() {
        return type;
    }

    /**
     * 设置：渠道-type
     *
     * @param type
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取：渠道-plat
     *
     * @return plat
     */
    public String getPlat() {
        return plat;
    }

    /**
     * 设置：渠道-plat
     *
     * @param plat
     */
    public void setPlat(String plat) {
        this.plat = plat == null ? null : plat.trim();
    }

    /**
     * 获取：渠道-send_store_id
     *
     * @return send_store_id
     */
    public String getSendStoreId() {
        return sendStoreId;
    }

    /**
     * 设置：渠道-send_store_id
     *
     * @param sendStoreId
     */
    public void setSendStoreId(String sendStoreId) {
        this.sendStoreId = sendStoreId == null ? null : sendStoreId.trim();
    }

    /**
     * 获取：渠道-refund_store_id
     *
     * @return refund_store_id
     */
    public String getRefundStoreId() {
        return refundStoreId;
    }

    /**
     * 设置：渠道-refund_store_id
     *
     * @param refundStoreId
     */
    public void setRefundStoreId(String refundStoreId) {
        this.refundStoreId = refundStoreId == null ? null : refundStoreId.trim();
    }

    /**
     * 获取：渠道-link_man
     *
     * @return link_man
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * 设置：渠道-link_man
     *
     * @param linkMan
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * 获取：渠道-mobile
     *
     * @return mobile
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 设置：渠道-mobile
     *
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * 获取：渠道-merchant_code
     *
     * @return merchant_code
     */
    public String getMerchantCode() {
        return merchantCode;
    }

    /**
     * 设置：渠道-merchant_code
     *
     * @param merchantCode
     */
    public void setMerchantCode(String merchantCode) {
        this.merchantCode = merchantCode == null ? null : merchantCode.trim();
    }

    /**
     * 获取：渠道-gmt_create
     *
     * @return gmt_create
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * 设置：渠道-gmt_create
     *
     * @param gmtCreate
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * 获取：渠道-gmt_modified
     *
     * @return gmt_modified
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * 设置：渠道-gmt_modified
     *
     * @param gmtModified
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * 获取：渠道-creator
     *
     * @return creator
     */
    public String getCreator() {
        return creator;
    }

    /**
     * 设置：渠道-creator
     *
     * @param creator
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * 获取：渠道-modifier
     *
     * @return modifier
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * 设置：渠道-modifier
     *
     * @param modifier
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * 获取：渠道-state
     *
     * @return state
     */
    public String getState() {
        return state;
    }

    /**
     * 设置：渠道-state
     *
     * @param state
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }
}