package com.ztesoft.zsmart.nros.sbc.user.server.dao.dataobject.generator;

import java.io.Serializable;
import java.util.Date;

/**
 * StaffDO
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-04-23
 */
public class StaffDO implements Serializable {
    /**
     * StaffDO-staff_id
     */
    private Long staffId;

    /**
     * StaffDO-staff_name
     */
    private String staffName;

    /**
     * StaffDO-staff_code
     */
    private String staffCode;

    /**
     * StaffDO-email
     */
    private String email;

    /**
     * StaffDO-phone
     */
    private String phone;

    /**
     * StaffDO-address
     */
    private String address;

    /**
     * StaffDO-created_date
     */
    private Date createdDate;

    /**
     * StaffDO-state
     */
    private String state;

    /**
     * StaffDO-state_date
     */
    private Date stateDate;

    /**
     * StaffDO-user_id
     */
    private Integer userId;

    /**
     * StaffDO-ext_str_01
     */
    private String extStr01;

    /**
     * StaffDO-ext_str_02
     */
    private String extStr02;

    /**
     * StaffDO-ext_str_03
     */
    private String extStr03;

    /**
     * StaffDO-ext_str_04
     */
    private String extStr04;

    /**
     * StaffDO-ext_str_05
     */
    private String extStr05;

    /**
     * StaffDO-ext_str_06
     */
    private String extStr06;

    /**
     * StaffDO-ext_str_07
     */
    private String extStr07;

    /**
     * StaffDO-ext_str_08
     */
    private String extStr08;

    /**
     * StaffDO-ext_str_09
     */
    private String extStr09;

    /**
     * StaffDO-ext_str_10
     */
    private String extStr10;

    /**
     * StaffDO-ext_str_11
     */
    private String extStr11;

    /**
     * StaffDO-ext_str_12
     */
    private String extStr12;

    /**
     * StaffDO-ext_num_01
     */
    private Integer extNum01;

    /**
     * StaffDO-ext_num_02
     */
    private Integer extNum02;

    /**
     * StaffDO-ext_dat_01
     */
    private Date extDat01;

    /**
     * StaffDO-update_date
     */
    private Date updateDate;

    /**
     * StaffDO-ext_dat_02
     */
    private Date extDat02;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：StaffDO-staff_id
     *
     * @return staff_id
     */
    public Long getStaffId() {
        return staffId;
    }

    /**
     * 设置：StaffDO-staff_id
     *
     * @param staffId
     */
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    /**
     * 获取：StaffDO-staff_name
     *
     * @return staff_name
     */
    public String getStaffName() {
        return staffName;
    }

    /**
     * 设置：StaffDO-staff_name
     *
     * @param staffName
     */
    public void setStaffName(String staffName) {
        this.staffName = staffName == null ? null : staffName.trim();
    }

    /**
     * 获取：StaffDO-staff_code
     *
     * @return staff_code
     */
    public String getStaffCode() {
        return staffCode;
    }

    /**
     * 设置：StaffDO-staff_code
     *
     * @param staffCode
     */
    public void setStaffCode(String staffCode) {
        this.staffCode = staffCode == null ? null : staffCode.trim();
    }

    /**
     * 获取：StaffDO-email
     *
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置：StaffDO-email
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 获取：StaffDO-phone
     *
     * @return phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置：StaffDO-phone
     *
     * @param phone
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取：StaffDO-address
     *
     * @return address
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置：StaffDO-address
     *
     * @param address
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取：StaffDO-created_date
     *
     * @return created_date
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * 设置：StaffDO-created_date
     *
     * @param createdDate
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * 获取：StaffDO-state
     *
     * @return state
     */
    public String getState() {
        return state;
    }

    /**
     * 设置：StaffDO-state
     *
     * @param state
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * 获取：StaffDO-state_date
     *
     * @return state_date
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * 设置：StaffDO-state_date
     *
     * @param stateDate
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * 获取：StaffDO-user_id
     *
     * @return user_id
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * 设置：StaffDO-user_id
     *
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取：StaffDO-ext_str_01
     *
     * @return ext_str_01
     */
    public String getExtStr01() {
        return extStr01;
    }

    /**
     * 设置：StaffDO-ext_str_01
     *
     * @param extStr01
     */
    public void setExtStr01(String extStr01) {
        this.extStr01 = extStr01 == null ? null : extStr01.trim();
    }

    /**
     * 获取：StaffDO-ext_str_02
     *
     * @return ext_str_02
     */
    public String getExtStr02() {
        return extStr02;
    }

    /**
     * 设置：StaffDO-ext_str_02
     *
     * @param extStr02
     */
    public void setExtStr02(String extStr02) {
        this.extStr02 = extStr02 == null ? null : extStr02.trim();
    }

    /**
     * 获取：StaffDO-ext_str_03
     *
     * @return ext_str_03
     */
    public String getExtStr03() {
        return extStr03;
    }

    /**
     * 设置：StaffDO-ext_str_03
     *
     * @param extStr03
     */
    public void setExtStr03(String extStr03) {
        this.extStr03 = extStr03 == null ? null : extStr03.trim();
    }

    /**
     * 获取：StaffDO-ext_str_04
     *
     * @return ext_str_04
     */
    public String getExtStr04() {
        return extStr04;
    }

    /**
     * 设置：StaffDO-ext_str_04
     *
     * @param extStr04
     */
    public void setExtStr04(String extStr04) {
        this.extStr04 = extStr04 == null ? null : extStr04.trim();
    }

    /**
     * 获取：StaffDO-ext_str_05
     *
     * @return ext_str_05
     */
    public String getExtStr05() {
        return extStr05;
    }

    /**
     * 设置：StaffDO-ext_str_05
     *
     * @param extStr05
     */
    public void setExtStr05(String extStr05) {
        this.extStr05 = extStr05 == null ? null : extStr05.trim();
    }

    /**
     * 获取：StaffDO-ext_str_06
     *
     * @return ext_str_06
     */
    public String getExtStr06() {
        return extStr06;
    }

    /**
     * 设置：StaffDO-ext_str_06
     *
     * @param extStr06
     */
    public void setExtStr06(String extStr06) {
        this.extStr06 = extStr06 == null ? null : extStr06.trim();
    }

    /**
     * 获取：StaffDO-ext_str_07
     *
     * @return ext_str_07
     */
    public String getExtStr07() {
        return extStr07;
    }

    /**
     * 设置：StaffDO-ext_str_07
     *
     * @param extStr07
     */
    public void setExtStr07(String extStr07) {
        this.extStr07 = extStr07 == null ? null : extStr07.trim();
    }

    /**
     * 获取：StaffDO-ext_str_08
     *
     * @return ext_str_08
     */
    public String getExtStr08() {
        return extStr08;
    }

    /**
     * 设置：StaffDO-ext_str_08
     *
     * @param extStr08
     */
    public void setExtStr08(String extStr08) {
        this.extStr08 = extStr08 == null ? null : extStr08.trim();
    }

    /**
     * 获取：StaffDO-ext_str_09
     *
     * @return ext_str_09
     */
    public String getExtStr09() {
        return extStr09;
    }

    /**
     * 设置：StaffDO-ext_str_09
     *
     * @param extStr09
     */
    public void setExtStr09(String extStr09) {
        this.extStr09 = extStr09 == null ? null : extStr09.trim();
    }

    /**
     * 获取：StaffDO-ext_str_10
     *
     * @return ext_str_10
     */
    public String getExtStr10() {
        return extStr10;
    }

    /**
     * 设置：StaffDO-ext_str_10
     *
     * @param extStr10
     */
    public void setExtStr10(String extStr10) {
        this.extStr10 = extStr10 == null ? null : extStr10.trim();
    }

    /**
     * 获取：StaffDO-ext_str_11
     *
     * @return ext_str_11
     */
    public String getExtStr11() {
        return extStr11;
    }

    /**
     * 设置：StaffDO-ext_str_11
     *
     * @param extStr11
     */
    public void setExtStr11(String extStr11) {
        this.extStr11 = extStr11 == null ? null : extStr11.trim();
    }

    /**
     * 获取：StaffDO-ext_str_12
     *
     * @return ext_str_12
     */
    public String getExtStr12() {
        return extStr12;
    }

    /**
     * 设置：StaffDO-ext_str_12
     *
     * @param extStr12
     */
    public void setExtStr12(String extStr12) {
        this.extStr12 = extStr12 == null ? null : extStr12.trim();
    }

    /**
     * 获取：StaffDO-ext_num_01
     *
     * @return ext_num_01
     */
    public Integer getExtNum01() {
        return extNum01;
    }

    /**
     * 设置：StaffDO-ext_num_01
     *
     * @param extNum01
     */
    public void setExtNum01(Integer extNum01) {
        this.extNum01 = extNum01;
    }

    /**
     * 获取：StaffDO-ext_num_02
     *
     * @return ext_num_02
     */
    public Integer getExtNum02() {
        return extNum02;
    }

    /**
     * 设置：StaffDO-ext_num_02
     *
     * @param extNum02
     */
    public void setExtNum02(Integer extNum02) {
        this.extNum02 = extNum02;
    }

    /**
     * 获取：StaffDO-ext_dat_01
     *
     * @return ext_dat_01
     */
    public Date getExtDat01() {
        return extDat01;
    }

    /**
     * 设置：StaffDO-ext_dat_01
     *
     * @param extDat01
     */
    public void setExtDat01(Date extDat01) {
        this.extDat01 = extDat01;
    }

    /**
     * 获取：StaffDO-update_date
     *
     * @return update_date
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * 设置：StaffDO-update_date
     *
     * @param updateDate
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * 获取：StaffDO-ext_dat_02
     *
     * @return ext_dat_02
     */
    public Date getExtDat02() {
        return extDat02;
    }

    /**
     * 设置：StaffDO-ext_dat_02
     *
     * @param extDat02
     */
    public void setExtDat02(Date extDat02) {
        this.extDat02 = extDat02;
    }
}