package com.ztesoft.zsmart.nros.sbc.user.server.dao.dataobject.generator;

import java.io.Serializable;
import java.util.Date;

/**
 * 门店详情信息表
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-04-20
 */
public class StoreDO implements Serializable {
    /**
     * 门店详情信息表-主键
     */
    private Long id;

    /**
     * 门店详情信息表-bfm_org的主键
     */
    private Long orgId;

    /**
     * 门店详情信息表-门店名称
     */
    private String name;

    /**
     * 门店详情信息表-门店编码
     */
    private String number;

    /**
     * 门店详情信息表-省
     */
    private String province;

    /**
     * 门店详情信息表-区
     */
    private String area;

    /**
     * 门店详情信息表-市
     */
    private String city;

    /**
     * 门店详情信息表-纬度
     */
    private String latitude;

    /**
     * 门店详情信息表-经度
     */
    private String longitude;

    /**
     * 门店详情信息表-详细地址
     */
    private String address;

    /**
     * 门店详情信息表-联系人姓名
     */
    private String linkMan;

    /**
     * 门店详情信息表-联系人手机号
     */
    private String mobile;

    /**
     * 门店详情信息表-联系电话
     */
    private String phone;

    /**
     * 门店详情信息表-创建时间
     */
    private Date createTime;

    /**
     * 门店详情信息表-更新时间
     */
    private Date updateTime;

    /**
     * 门店详情信息表-A有效,X无效
     */
    private String state;

    /**
     * 门店详情信息表-邮政编码
     */
    private String zipCode;

    /**
     * 门店详情信息表-省代码
     */
    private Long provinceId;

    /**
     * 门店详情信息表-市代码
     */
    private Long cityId;

    /**
     * 门店详情信息表-区代码
     */
    private Long areaId;

    /**
     * 门店详情信息表-同步状态
     */
    private String synStatus;

    /**
     * 门店详情信息表-mdm门店编码
     */
    private String mdmNumber;

    /**
     * 门店详情信息表-jde对应的门店地址号
     */
    private Long jdeAddressCode;

    /**
     * 门店详情信息表-jde对应的公司键
     */
    private String jdeCompanyCode;

    /**
     * 门店详情信息表-与JDE交互的门店编码
     */
    private String jdeNumber;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：门店详情信息表-主键
     *
     * @return 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：门店详情信息表-主键
     *
     * @param id 门店详情信息表-主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：门店详情信息表-bfm_org的主键
     *
     * @return bfm_org的主键
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置：门店详情信息表-bfm_org的主键
     *
     * @param orgId 门店详情信息表-bfm_org的主键
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取：门店详情信息表-门店名称
     *
     * @return 门店名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置：门店详情信息表-门店名称
     *
     * @param name 门店详情信息表-门店名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取：门店详情信息表-门店编码
     *
     * @return 门店编码
     */
    public String getNumber() {
        return number;
    }

    /**
     * 设置：门店详情信息表-门店编码
     *
     * @param number 门店详情信息表-门店编码
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * 获取：门店详情信息表-省
     *
     * @return 省
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置：门店详情信息表-省
     *
     * @param province 门店详情信息表-省
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * 获取：门店详情信息表-区
     *
     * @return 区
     */
    public String getArea() {
        return area;
    }

    /**
     * 设置：门店详情信息表-区
     *
     * @param area 门店详情信息表-区
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * 获取：门店详情信息表-市
     *
     * @return 市
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置：门店详情信息表-市
     *
     * @param city 门店详情信息表-市
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取：门店详情信息表-纬度
     *
     * @return 纬度
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * 设置：门店详情信息表-纬度
     *
     * @param latitude 门店详情信息表-纬度
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * 获取：门店详情信息表-经度
     *
     * @return 经度
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * 设置：门店详情信息表-经度
     *
     * @param longitude 门店详情信息表-经度
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * 获取：门店详情信息表-详细地址
     *
     * @return 详细地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置：门店详情信息表-详细地址
     *
     * @param address 门店详情信息表-详细地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取：门店详情信息表-联系人姓名
     *
     * @return 联系人姓名
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * 设置：门店详情信息表-联系人姓名
     *
     * @param linkMan 门店详情信息表-联系人姓名
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * 获取：门店详情信息表-联系人手机号
     *
     * @return 联系人手机号
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 设置：门店详情信息表-联系人手机号
     *
     * @param mobile 门店详情信息表-联系人手机号
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * 获取：门店详情信息表-联系电话
     *
     * @return 联系电话
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置：门店详情信息表-联系电话
     *
     * @param phone 门店详情信息表-联系电话
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取：门店详情信息表-创建时间
     *
     * @return 创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * 设置：门店详情信息表-创建时间
     *
     * @param createTime 门店详情信息表-创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取：门店详情信息表-更新时间
     *
     * @return 更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * 设置：门店详情信息表-更新时间
     *
     * @param updateTime 门店详情信息表-更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取：门店详情信息表-A有效,X无效
     *
     * @return A有效,X无效
     */
    public String getState() {
        return state;
    }

    /**
     * 设置：门店详情信息表-A有效,X无效
     *
     * @param state 门店详情信息表-A有效,X无效
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * 获取：门店详情信息表-邮政编码
     *
     * @return 邮政编码
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * 设置：门店详情信息表-邮政编码
     *
     * @param zipCode 门店详情信息表-邮政编码
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * 获取：门店详情信息表-省代码
     *
     * @return 省代码
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * 设置：门店详情信息表-省代码
     *
     * @param provinceId 门店详情信息表-省代码
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * 获取：门店详情信息表-市代码
     *
     * @return 市代码
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * 设置：门店详情信息表-市代码
     *
     * @param cityId 门店详情信息表-市代码
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * 获取：门店详情信息表-区代码
     *
     * @return 区代码
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * 设置：门店详情信息表-区代码
     *
     * @param areaId 门店详情信息表-区代码
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * 获取：门店详情信息表-同步状态
     *
     * @return 同步状态
     */
    public String getSynStatus() {
        return synStatus;
    }

    /**
     * 设置：门店详情信息表-同步状态
     *
     * @param synStatus 门店详情信息表-同步状态
     */
    public void setSynStatus(String synStatus) {
        this.synStatus = synStatus == null ? null : synStatus.trim();
    }

    /**
     * 获取：门店详情信息表-mdm门店编码
     *
     * @return mdm门店编码
     */
    public String getMdmNumber() {
        return mdmNumber;
    }

    /**
     * 设置：门店详情信息表-mdm门店编码
     *
     * @param mdmNumber 门店详情信息表-mdm门店编码
     */
    public void setMdmNumber(String mdmNumber) {
        this.mdmNumber = mdmNumber == null ? null : mdmNumber.trim();
    }

    /**
     * 获取：门店详情信息表-jde对应的门店地址号
     *
     * @return jde对应的门店地址号
     */
    public Long getJdeAddressCode() {
        return jdeAddressCode;
    }

    /**
     * 设置：门店详情信息表-jde对应的门店地址号
     *
     * @param jdeAddressCode 门店详情信息表-jde对应的门店地址号
     */
    public void setJdeAddressCode(Long jdeAddressCode) {
        this.jdeAddressCode = jdeAddressCode;
    }

    /**
     * 获取：门店详情信息表-jde对应的公司键
     *
     * @return jde对应的公司键
     */
    public String getJdeCompanyCode() {
        return jdeCompanyCode;
    }

    /**
     * 设置：门店详情信息表-jde对应的公司键
     *
     * @param jdeCompanyCode 门店详情信息表-jde对应的公司键
     */
    public void setJdeCompanyCode(String jdeCompanyCode) {
        this.jdeCompanyCode = jdeCompanyCode == null ? null : jdeCompanyCode.trim();
    }

    /**
     * 获取：门店详情信息表-与JDE交互的门店编码
     *
     * @return 与JDE交互的门店编码
     */
    public String getJdeNumber() {
        return jdeNumber;
    }

    /**
     * 设置：门店详情信息表-与JDE交互的门店编码
     *
     * @param jdeNumber 门店详情信息表-与JDE交互的门店编码
     */
    public void setJdeNumber(String jdeNumber) {
        this.jdeNumber = jdeNumber == null ? null : jdeNumber.trim();
    }
}