package com.ztesoft.zsmart.nros.sbc.user.server.dao.dataobject.generator;

import java.io.Serializable;
import java.util.Date;

/**
 * T_BFM_USER_ID_SEQ
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-04-23
 */
public class UserDO implements Serializable {
    /**
     * T_BFM_USER_ID_SEQ-user_id
     */
    private Long userId;

    /**
     * T_BFM_USER_ID_SEQ-user_name
     */
    private String userName;

    /**
     * T_BFM_USER_ID_SEQ-email
     */
    private String email;

    /**
     * T_BFM_USER_ID_SEQ-phone
     */
    private String phone;

    /**
     * T_BFM_USER_ID_SEQ-工号,login
     */
    private String userCode;

    /**
     * T_BFM_USER_ID_SEQ-pwd
     */
    private String pwd;

    /**
     * T_BFM_USER_ID_SEQ-address
     */
    private String address;

    /**
     * T_BFM_USER_ID_SEQ-memo
     */
    private String memo;

    /**
     * T_BFM_USER_ID_SEQ-user_eff_date
     */
    private Date userEffDate;

    /**
     * T_BFM_USER_ID_SEQ-空表示永不实效
     */
    private Date userExpDate;

    /**
     * T_BFM_USER_ID_SEQ-created_date
     */
    private Date createdDate;

    /**
     * T_BFM_USER_ID_SEQ-A-在用，X-失效
     */
    private String state;

    /**
     * T_BFM_USER_ID_SEQ-state_date
     */
    private Date stateDate;

    /**
     * T_BFM_USER_ID_SEQ-是否锁定，'Y'-锁定，'N'-没有锁定，null表示'N'
     */
    private String isLocked;

    /**
     * T_BFM_USER_ID_SEQ-密码过期时间，空表示永不过期
     */
    private Date pwdExpDate;

    /**
     * T_BFM_USER_ID_SEQ-登录失败次数，空表示0
     */
    private Integer loginFail;

    /**
     * T_BFM_USER_ID_SEQ-unlock_date
     */
    private Date unlockDate;

    /**
     * T_BFM_USER_ID_SEQ-portal_id
     */
    private Integer portalId;

    /**
     * T_BFM_USER_ID_SEQ-update_date
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：T_BFM_USER_ID_SEQ-user_id
     *
     * @return user_id
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-user_id
     *
     * @param userId
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-user_name
     *
     * @return user_name
     */
    public String getUserName() {
        return userName;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-user_name
     *
     * @param userName
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-email
     *
     * @return email
     */
    public String getEmail() {
        return email;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-email
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-phone
     *
     * @return phone
     */
    public String getPhone() {
        return phone;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-phone
     *
     * @param phone
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-工号,login
     *
     * @return 工号,login
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-工号,login
     *
     * @param userCode T_BFM_USER_ID_SEQ-工号,login
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-pwd
     *
     * @return pwd
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-pwd
     *
     * @param pwd
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-address
     *
     * @return address
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-address
     *
     * @param address
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-memo
     *
     * @return memo
     */
    public String getMemo() {
        return memo;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-memo
     *
     * @param memo
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-user_eff_date
     *
     * @return user_eff_date
     */
    public Date getUserEffDate() {
        return userEffDate;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-user_eff_date
     *
     * @param userEffDate
     */
    public void setUserEffDate(Date userEffDate) {
        this.userEffDate = userEffDate;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-空表示永不实效
     *
     * @return 空表示永不实效
     */
    public Date getUserExpDate() {
        return userExpDate;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-空表示永不实效
     *
     * @param userExpDate T_BFM_USER_ID_SEQ-空表示永不实效
     */
    public void setUserExpDate(Date userExpDate) {
        this.userExpDate = userExpDate;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-created_date
     *
     * @return created_date
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-created_date
     *
     * @param createdDate
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-A-在用，X-失效
     *
     * @return A-在用，X-失效
     */
    public String getState() {
        return state;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-A-在用，X-失效
     *
     * @param state T_BFM_USER_ID_SEQ-A-在用，X-失效
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-state_date
     *
     * @return state_date
     */
    public Date getStateDate() {
        return stateDate;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-state_date
     *
     * @param stateDate
     */
    public void setStateDate(Date stateDate) {
        this.stateDate = stateDate;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-是否锁定，'Y'-锁定，'N'-没有锁定，null表示'N'
     *
     * @return 是否锁定，'Y'-锁定，'N'-没有锁定，null表示'N'
     */
    public String getIsLocked() {
        return isLocked;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-是否锁定，'Y'-锁定，'N'-没有锁定，null表示'N'
     *
     * @param isLocked T_BFM_USER_ID_SEQ-是否锁定，'Y'-锁定，'N'-没有锁定，null表示'N'
     */
    public void setIsLocked(String isLocked) {
        this.isLocked = isLocked == null ? null : isLocked.trim();
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-密码过期时间，空表示永不过期
     *
     * @return 密码过期时间，空表示永不过期
     */
    public Date getPwdExpDate() {
        return pwdExpDate;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-密码过期时间，空表示永不过期
     *
     * @param pwdExpDate T_BFM_USER_ID_SEQ-密码过期时间，空表示永不过期
     */
    public void setPwdExpDate(Date pwdExpDate) {
        this.pwdExpDate = pwdExpDate;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-登录失败次数，空表示0
     *
     * @return 登录失败次数，空表示0
     */
    public Integer getLoginFail() {
        return loginFail;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-登录失败次数，空表示0
     *
     * @param loginFail T_BFM_USER_ID_SEQ-登录失败次数，空表示0
     */
    public void setLoginFail(Integer loginFail) {
        this.loginFail = loginFail;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-unlock_date
     *
     * @return unlock_date
     */
    public Date getUnlockDate() {
        return unlockDate;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-unlock_date
     *
     * @param unlockDate
     */
    public void setUnlockDate(Date unlockDate) {
        this.unlockDate = unlockDate;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-portal_id
     *
     * @return portal_id
     */
    public Integer getPortalId() {
        return portalId;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-portal_id
     *
     * @param portalId
     */
    public void setPortalId(Integer portalId) {
        this.portalId = portalId;
    }

    /**
     * 获取：T_BFM_USER_ID_SEQ-update_date
     *
     * @return update_date
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * 设置：T_BFM_USER_ID_SEQ-update_date
     *
     * @param updateDate
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}