package com.ztesoft.zsmart.nros.sbc.user.server.dao.dataobject.generator;

import com.ztesoft.zsmart.nros.common.model.BaseModel;
import java.io.Serializable;

/**
 * UserOrgPrivDO
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-06-04
 */
public class UserOrgPrivDO extends BaseModel implements Serializable {
    /**
     * UserOrgPrivDO-用户主键
     */
    private Long userId;

    /**
     * UserOrgPrivDO-机构主键
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：UserOrgPrivDO-用户主键
     *
     * @return 用户主键
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * 设置：UserOrgPrivDO-用户主键
     *
     * @param userId UserOrgPrivDO-用户主键
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 获取：UserOrgPrivDO-机构主键
     *
     * @return 机构主键
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置：UserOrgPrivDO-机构主键
     *
     * @param orgId UserOrgPrivDO-机构主键
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }
}