package com.ztesoft.zsmart.nros.sbc.user.server.dao.dataobject.generator;

import java.io.Serializable;

/**
 * 同仁堂仓库实体
 * @author 浩鲸云计算科技股份有限公司
 * @date 2019-04-20
 */
public class WarehouseDO implements Serializable {
    /**
     * 同仁堂仓库实体-主键
     */
    private Long id;

    /**
     * 同仁堂仓库实体-bfm_org的主键
     */
    private Long orgId;

    /**
     * 同仁堂仓库实体-仓库名称
     */
    private String name;

    /**
     * 同仁堂仓库实体-仓库编号
     */
    private String number;

    /**
     * 同仁堂仓库实体-详细地址
     */
    private String address;

    /**
     * 同仁堂仓库实体-省名称
     */
    private String province;

    /**
     * 同仁堂仓库实体-市名称
     */
    private String city;

    /**
     * 同仁堂仓库实体-区域名称
     */
    private String area;

    /**
     * 同仁堂仓库实体-联系人姓名
     */
    private String contact;

    /**
     * 同仁堂仓库实体-状态A有效,X无效
     */
    private String state;

    /**
     * 同仁堂仓库实体-是否启用0,启用,1禁用
     */
    private String enable;

    /**
     * 同仁堂仓库实体-分机号
     */
    private String extensionNumber;

    /**
     * 同仁堂仓库实体-联系人手机号
     */
    private String mobile;

    /**
     * 同仁堂仓库实体-对应门店编码
     */
    private Long storeId;

    /**
     * 同仁堂仓库实体-对应门店名称
     */
    private String storeName;

    /**
     * 同仁堂仓库实体-电话
     */
    private String telephone;

    /**
     * 同仁堂仓库实体-仓库类型 1：实体仓 2：门店仓 3：售药机仓
     */
    private String type;

    /**
     * 同仁堂仓库实体-邮编
     */
    private String zipCode;

    /**
     * 同仁堂仓库实体-是否共享：0共享，1不共享
     */
    private String shareFlag;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取：同仁堂仓库实体-主键
     *
     * @return 主键
     */
    public Long getId() {
        return id;
    }

    /**
     * 设置：同仁堂仓库实体-主键
     *
     * @param id 同仁堂仓库实体-主键
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 获取：同仁堂仓库实体-bfm_org的主键
     *
     * @return bfm_org的主键
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * 设置：同仁堂仓库实体-bfm_org的主键
     *
     * @param orgId 同仁堂仓库实体-bfm_org的主键
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * 获取：同仁堂仓库实体-仓库名称
     *
     * @return 仓库名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置：同仁堂仓库实体-仓库名称
     *
     * @param name 同仁堂仓库实体-仓库名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取：同仁堂仓库实体-仓库编号
     *
     * @return 仓库编号
     */
    public String getNumber() {
        return number;
    }

    /**
     * 设置：同仁堂仓库实体-仓库编号
     *
     * @param number 同仁堂仓库实体-仓库编号
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * 获取：同仁堂仓库实体-详细地址
     *
     * @return 详细地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * 设置：同仁堂仓库实体-详细地址
     *
     * @param address 同仁堂仓库实体-详细地址
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 获取：同仁堂仓库实体-省名称
     *
     * @return 省名称
     */
    public String getProvince() {
        return province;
    }

    /**
     * 设置：同仁堂仓库实体-省名称
     *
     * @param province 同仁堂仓库实体-省名称
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * 获取：同仁堂仓库实体-市名称
     *
     * @return 市名称
     */
    public String getCity() {
        return city;
    }

    /**
     * 设置：同仁堂仓库实体-市名称
     *
     * @param city 同仁堂仓库实体-市名称
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * 获取：同仁堂仓库实体-区域名称
     *
     * @return 区域名称
     */
    public String getArea() {
        return area;
    }

    /**
     * 设置：同仁堂仓库实体-区域名称
     *
     * @param area 同仁堂仓库实体-区域名称
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * 获取：同仁堂仓库实体-联系人姓名
     *
     * @return 联系人姓名
     */
    public String getContact() {
        return contact;
    }

    /**
     * 设置：同仁堂仓库实体-联系人姓名
     *
     * @param contact 同仁堂仓库实体-联系人姓名
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * 获取：同仁堂仓库实体-状态A有效,X无效
     *
     * @return 状态A有效,X无效
     */
    public String getState() {
        return state;
    }

    /**
     * 设置：同仁堂仓库实体-状态A有效,X无效
     *
     * @param state 同仁堂仓库实体-状态A有效,X无效
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * 获取：同仁堂仓库实体-是否启用0,启用,1禁用
     *
     * @return 是否启用0,启用,1禁用
     */
    public String getEnable() {
        return enable;
    }

    /**
     * 设置：同仁堂仓库实体-是否启用0,启用,1禁用
     *
     * @param enable 同仁堂仓库实体-是否启用0,启用,1禁用
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * 获取：同仁堂仓库实体-分机号
     *
     * @return 分机号
     */
    public String getExtensionNumber() {
        return extensionNumber;
    }

    /**
     * 设置：同仁堂仓库实体-分机号
     *
     * @param extensionNumber 同仁堂仓库实体-分机号
     */
    public void setExtensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber == null ? null : extensionNumber.trim();
    }

    /**
     * 获取：同仁堂仓库实体-联系人手机号
     *
     * @return 联系人手机号
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * 设置：同仁堂仓库实体-联系人手机号
     *
     * @param mobile 同仁堂仓库实体-联系人手机号
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * 获取：同仁堂仓库实体-对应门店编码
     *
     * @return 对应门店编码
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * 设置：同仁堂仓库实体-对应门店编码
     *
     * @param storeId 同仁堂仓库实体-对应门店编码
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * 获取：同仁堂仓库实体-对应门店名称
     *
     * @return 对应门店名称
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * 设置：同仁堂仓库实体-对应门店名称
     *
     * @param storeName 同仁堂仓库实体-对应门店名称
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * 获取：同仁堂仓库实体-电话
     *
     * @return 电话
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * 设置：同仁堂仓库实体-电话
     *
     * @param telephone 同仁堂仓库实体-电话
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * 获取：同仁堂仓库实体-仓库类型 1：实体仓 2：门店仓 3：售药机仓
     *
     * @return 仓库类型 1：实体仓 2：门店仓 3：售药机仓
     */
    public String getType() {
        return type;
    }

    /**
     * 设置：同仁堂仓库实体-仓库类型 1：实体仓 2：门店仓 3：售药机仓
     *
     * @param type 同仁堂仓库实体-仓库类型 1：实体仓 2：门店仓 3：售药机仓
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取：同仁堂仓库实体-邮编
     *
     * @return 邮编
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * 设置：同仁堂仓库实体-邮编
     *
     * @param zipCode 同仁堂仓库实体-邮编
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * 获取：同仁堂仓库实体-是否共享：0共享，1不共享
     *
     * @return 是否共享：0共享，1不共享
     */
    public String getShareFlag() {
        return shareFlag;
    }

    /**
     * 设置：同仁堂仓库实体-是否共享：0共享，1不共享
     *
     * @param shareFlag 同仁堂仓库实体-是否共享：0共享，1不共享
     */
    public void setShareFlag(String shareFlag) {
        this.shareFlag = shareFlag == null ? null : shareFlag.trim();
    }
}