package com.ztesoft.zsmart.nros.sbc.user.client.model.dto;

import lombok.Data;

import java.util.Date;

/**
 * 商家
 *
 * @author bin.yu
 * @create 2019-04-24 17:04
 **/
@Data
public class MerchantDTO {

    /**
     * MerchantDO-主键
     */
    private Long id;

    /**
     * MerchantDO-创建时间
     */
    private Date gmtCreate;

    /**
     * MerchantDO-修改时间
     */
    private Date gmtModified;

    /**
     * MerchantDO-创建者
     */
    private String creator;

    /**
     * MerchantDO-修改者
     */
    private String modifier;

    /**
     * MerchantDO-乐观锁版本号
     */
    private Long version;

    /**
     * MerchantDO-是否启用(0,1)
     */
    private String active;

    /**
     * MerchantDO-机构逻辑主键(同盒马merchant_id)
     */
    private Long orgId;

    /**
     * MerchantDO-名称
     */
    private String name;

    /**
     * MerchantDO-负责人
     */
    private String principal;

    /**
     * MerchantDO-联系人电话
     */
    private String phone;

    /**
     * MerchantDO-传真
     */
    private String fax;

    /**
     * MerchantDO-支付宝账号
     */
    private String alipayAccount;

    /**
     * MerchantDO-分账费率
     */
    private Long ledgerAccountRate;

    /**
     * MerchantDO-备注
     */
    private String remark;

    /**
     * MerchantDO-编码
     */
    private String code;

    /**
     * MerchantDO-省
     */
    private String province;

    /**
     * MerchantDO-市
     */
    private String city;

    /**
     * MerchantDO-区
     */
    private String area;

    /**
     * MerchantDO-详细地址
     */
    private String address;

    /**
     * MerchantDO-扩展字段
     */
    private String extension;

    /**
     * MerchantDO-上级机构id
     */
    private Long parentOrgId;

    /**
     * MerchantDO-电子身份标签
     */
    private String appKey;

    /**
     * MerchantDO-商家类型,1.正式2.测试
     */
    private String flag;

    /**
     * MerchantDO-合同编码
     */
    private String contractCode;

    /**
     * MerchantDO-合同创建时间
     */
    private Date contractCreateTime;

    /**
     * MerchantDO-合同生效时间
     */
    private Date contractStartTime;

    /**
     * MerchantDO-合同终止时间
     */
    private Date contractEndTime;

    /**
     * MerchantDO-邮箱地址
     */
    private String email;

    /**
     * MerchantDO-state
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}
