package com.ztesoft.zsmart.nros.sbc.user.client.model.dto;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Created with IntelliJ IDEA.
 * Description:
 * User: yaodingw
 * Date: 2019-04-17
 * Time: 19:44
 */
@Data
public class StoreDTO implements Serializable {

    /**
     * 门店详情信息表-主键
     */
    private Long id;

    /**
     * 门店详情信息表-bfm_org的主键
     */
    private Long orgId;

    /**
     * 门店详情信息表-门店名称
     */
    private String name;

    /**
     * 门店详情信息表-门店编码
     */
    private String number;

    /**
     * 门店详情信息表-省
     */
    private String province;

    /**
     * 门店详情信息表-区
     */
    private String area;

    /**
     * 门店详情信息表-市
     */
    private String city;

    /**
     * 门店详情信息表-纬度
     */
    private String latitude;

    /**
     * 门店详情信息表-经度
     */
    private String longitude;

    /**
     * 门店详情信息表-详细地址
     */
    private String address;

    /**
     * 门店详情信息表-联系人姓名
     */
    private String linkMan;

    /**
     * 门店详情信息表-联系人手机号
     */
    private String mobile;

    /**
     * 门店详情信息表-联系电话
     */
    private String phone;

    /**
     * 门店详情信息表-创建时间
     */
    private Date createTime;

    /**
     * 门店详情信息表-更新时间
     */
    private Date updateTime;

    /**
     * 门店详情信息表-A有效,X无效
     */
    private String state;

    /**
     * 门店详情信息表-邮政编码
     */
    private String zipCode;

    /**
     * 门店详情信息表-省代码
     */
    private Long provinceId;

    /**
     * 门店详情信息表-市代码
     */
    private Long cityId;

    /**
     * 门店详情信息表-区代码
     */
    private Long areaId;

    /**
     * 门店详情信息表-同步状态
     */
    private String synStatus;

    /**
     * 门店详情信息表-mdm门店编码
     */
    private String mdmNumber;

    /**
     * 门店详情信息表-jde对应的门店地址号
     */
    private Long jdeAddressCode;

    /**
     * 门店详情信息表-jde对应的公司键
     */
    private String jdeCompanyCode;

    /**
     * 门店详情信息表-与JDE交互的门店编码
     */
    private String jdeNumber;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}
