package com.ztesoft.zsmart.nros.sbc.user.client.model.dto;

import lombok.Data;

import java.util.Date;

/**
 * 子公司
 *
 * @author bin.yu
 * @create 2019-04-24 17:03
 **/
@Data
public class SubsidiaryDTO {

    /**
     * SubsidiaryDO-主键
     */
    private Long id;

    /**
     * SubsidiaryDO-创建时间
     */
    private Date gmtCreate;

    /**
     * SubsidiaryDO-修改时间
     */
    private Date gmtModified;

    /**
     * SubsidiaryDO-创建者
     */
    private String creator;

    /**
     * SubsidiaryDO-修改者
     */
    private String modifier;

    /**
     * SubsidiaryDO-乐观锁版本号
     */
    private Long version;

    /**
     * SubsidiaryDO-是否启用(0,1)
     */
    private String active;

    /**
     * SubsidiaryDO-机构逻辑主键(同盒马merchant_id)
     */
    private Long orgId;

    /**
     * SubsidiaryDO-名称
     */
    private String name;

    /**
     * SubsidiaryDO-负责人
     */
    private String principal;

    /**
     * SubsidiaryDO-联系人电话
     */
    private String phone;

    /**
     * SubsidiaryDO-传真
     */
    private String fax;

    /**
     * SubsidiaryDO-支付宝账号
     */
    private String alipayAccount;

    /**
     * SubsidiaryDO-分账费率
     */
    private Long ledgerAccountRate;

    /**
     * SubsidiaryDO-备注
     */
    private String remark;

    /**
     * SubsidiaryDO-编码
     */
    private String code;

    /**
     * SubsidiaryDO-省
     */
    private String province;

    /**
     * SubsidiaryDO-市
     */
    private String city;

    /**
     * SubsidiaryDO-区
     */
    private String area;

    /**
     * SubsidiaryDO-详细地址
     */
    private String address;

    /**
     * SubsidiaryDO-扩展字段
     */
    private String extension;

    /**
     * SubsidiaryDO-上级机构id
     */
    private Long parentOrgId;

    /**
     * SubsidiaryDO-state
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     */
    private static final long serialVersionUID = 1L;
}
